// <auto-generated />
using java.io;
using JavaNETInterface.Jni;
using JavaNETInterface.Wrappers;

namespace java.util;

public unsafe class Scanner : JniObject
{
    public static JClass* Class { get; private set; }
    private static readonly Lock lockObject = new();
    private static bool initialized;

    private static JFieldID* buf_FieldId;
    private static JFieldID* BUFFER_SIZE_FieldId;
    private static JFieldID* position_FieldId;
    private static JFieldID* matcher_FieldId;
    private static JFieldID* delimPattern_FieldId;
    private static JFieldID* hasNextPattern_FieldId;
    private static JFieldID* hasNextPosition_FieldId;
    private static JFieldID* hasNextResult_FieldId;
    private static JFieldID* source_FieldId;
    private static JFieldID* sourceClosed_FieldId;
    private static JFieldID* needInput_FieldId;
    private static JFieldID* skipped_FieldId;
    private static JFieldID* savedScannerPosition_FieldId;
    private static JFieldID* typeCache_FieldId;
    private static JFieldID* matchValid_FieldId;
    private static JFieldID* closed_FieldId;
    private static JFieldID* radix_FieldId;
    private static JFieldID* defaultRadix_FieldId;
    private static JFieldID* locale_FieldId;
    private static JFieldID* patternCache_FieldId;
    private static JFieldID* lastException_FieldId;
    private static JFieldID* modCount_FieldId;
    private static JFieldID* WHITESPACE_PATTERN_FieldId;
    private static JFieldID* FIND_ANY_PATTERN_FieldId;
    private static JFieldID* NON_ASCII_DIGIT_FieldId;
    private static JFieldID* groupSeparator_FieldId;
    private static JFieldID* decimalSeparator_FieldId;
    private static JFieldID* nanString_FieldId;
    private static JFieldID* infinityString_FieldId;
    private static JFieldID* positivePrefix_FieldId;
    private static JFieldID* negativePrefix_FieldId;
    private static JFieldID* positiveSuffix_FieldId;
    private static JFieldID* negativeSuffix_FieldId;
    private static JFieldID* boolPattern_FieldId;
    private static JFieldID* BOOLEAN_PATTERN_FieldId;
    private static JFieldID* integerPattern_FieldId;
    private static JFieldID* digits_FieldId;
    private static JFieldID* non0Digit_FieldId;
    private static JFieldID* SIMPLE_GROUP_INDEX_FieldId;
    private static JFieldID* separatorPattern_FieldId;
    private static JFieldID* linePattern_FieldId;
    private static JFieldID* LINE_SEPARATOR_PATTERN_FieldId;
    private static JFieldID* LINE_PATTERN_FieldId;
    private static JFieldID* floatPattern_FieldId;
    private static JFieldID* decimalPattern_FieldId;
    private static JFieldID* _assertionsDisabled_FieldId;

    private static JMethodID* boolPattern_MethodId;
    private static JMethodID* buildIntegerPatternString_MethodId;
    private static JMethodID* integerPattern_MethodId;
    private static JMethodID* separatorPattern_MethodId;
    private static JMethodID* linePattern_MethodId;
    private static JMethodID* buildFloatAndDecimalPattern_MethodId;
    private static JMethodID* floatPattern_MethodId;
    private static JMethodID* decimalPattern_MethodId;
    private static JMethodID* Scanner0_MethodId;
    private static JMethodID* Scanner1_MethodId;
    private static JMethodID* Scanner2_MethodId;
    private static JMethodID* Scanner3_MethodId;
    private static JMethodID* Scanner4_MethodId;
    private static JMethodID* Scanner5_MethodId;
    private static JMethodID* Scanner6_MethodId;
    private static JMethodID* Scanner7_MethodId;
    private static JMethodID* Scanner8_MethodId;
    private static JMethodID* Scanner9_MethodId;
    private static JMethodID* Scanner10_MethodId;
    private static JMethodID* Scanner11_MethodId;
    private static JMethodID* Scanner12_MethodId;
    private static JMethodID* Scanner13_MethodId;
    private static JMethodID* Scanner14_MethodId;
    private static JMethodID* Scanner15_MethodId;
    private static JMethodID* toCharset_MethodId;
    private static JMethodID* makeReadable0_MethodId;
    private static JMethodID* makeReadable1_MethodId;
    private static JMethodID* makeReadable2_MethodId;
    private static JMethodID* makeReadable3_MethodId;
    private static JMethodID* makeReadable4_MethodId;
    private static JMethodID* toDecoder_MethodId;
    private static JMethodID* saveState_MethodId;
    private static JMethodID* revertState0_MethodId;
    private static JMethodID* revertState1_MethodId;
    private static JMethodID* cacheResult0_MethodId;
    private static JMethodID* cacheResult1_MethodId;
    private static JMethodID* clearCaches_MethodId;
    private static JMethodID* getCachedResult_MethodId;
    private static JMethodID* useTypeCache_MethodId;
    private static JMethodID* readInput_MethodId;
    private static JMethodID* makeSpace_MethodId;
    private static JMethodID* translateSavedIndexes_MethodId;
    private static JMethodID* throwFor_MethodId;
    private static JMethodID* hasTokenInBuffer_MethodId;
    private static JMethodID* getCompleteTokenInBuffer_MethodId;
    private static JMethodID* findPatternInBuffer_MethodId;
    private static JMethodID* matchPatternInBuffer_MethodId;
    private static JMethodID* ensureOpen_MethodId;
    private static JMethodID* close_MethodId;
    private static JMethodID* ioException_MethodId;
    private static JMethodID* delimiter_MethodId;
    private static JMethodID* useDelimiter0_MethodId;
    private static JMethodID* useDelimiter1_MethodId;
    private static JMethodID* locale_MethodId;
    private static JMethodID* useLocale_MethodId;
    private static JMethodID* radix_MethodId;
    private static JMethodID* useRadix_MethodId;
    private static JMethodID* setRadix_MethodId;
    private static JMethodID* match_MethodId;
    private static JMethodID* toString_MethodId;
    private static JMethodID* hasNext0_MethodId;
    private static JMethodID* hasNext1_MethodId;
    private static JMethodID* hasNext2_MethodId;
    private static JMethodID* next0_MethodId;
    private static JMethodID* next1_MethodId;
    private static JMethodID* next2_MethodId;
    private static JMethodID* next3_MethodId;
    private static JMethodID* remove_MethodId;
    private static JMethodID* hasNextLine_MethodId;
    private static JMethodID* nextLine_MethodId;
    private static JMethodID* findInLine0_MethodId;
    private static JMethodID* findInLine1_MethodId;
    private static JMethodID* findWithinHorizon0_MethodId;
    private static JMethodID* findWithinHorizon1_MethodId;
    private static JMethodID* skip0_MethodId;
    private static JMethodID* skip1_MethodId;
    private static JMethodID* hasNextBoolean_MethodId;
    private static JMethodID* nextBoolean_MethodId;
    private static JMethodID* hasNextByte0_MethodId;
    private static JMethodID* hasNextByte1_MethodId;
    private static JMethodID* nextByte0_MethodId;
    private static JMethodID* nextByte1_MethodId;
    private static JMethodID* hasNextShort0_MethodId;
    private static JMethodID* hasNextShort1_MethodId;
    private static JMethodID* nextShort0_MethodId;
    private static JMethodID* nextShort1_MethodId;
    private static JMethodID* hasNextInt0_MethodId;
    private static JMethodID* hasNextInt1_MethodId;
    private static JMethodID* processIntegerToken_MethodId;
    private static JMethodID* nextInt0_MethodId;
    private static JMethodID* nextInt1_MethodId;
    private static JMethodID* hasNextLong0_MethodId;
    private static JMethodID* hasNextLong1_MethodId;
    private static JMethodID* nextLong0_MethodId;
    private static JMethodID* nextLong1_MethodId;
    private static JMethodID* processFloatToken_MethodId;
    private static JMethodID* hasNextFloat_MethodId;
    private static JMethodID* nextFloat_MethodId;
    private static JMethodID* hasNextDouble_MethodId;
    private static JMethodID* nextDouble_MethodId;
    private static JMethodID* hasNextBigInteger0_MethodId;
    private static JMethodID* hasNextBigInteger1_MethodId;
    private static JMethodID* nextBigInteger0_MethodId;
    private static JMethodID* nextBigInteger1_MethodId;
    private static JMethodID* hasNextBigDecimal_MethodId;
    private static JMethodID* nextBigDecimal_MethodId;
    private static JMethodID* reset_MethodId;
    private static JMethodID* tokens_MethodId;
    private static JMethodID* findAll0_MethodId;
    private static JMethodID* findAll1_MethodId;

    public Scanner(JniEnv* env, JObject* obj) : base(env, obj)
        => Initialize(env);

    public static void Initialize(JniEnv* env)
    {
        lock(lockObject)
        {
            if(initialized)
                return;

            Class = env->FindClass("java/util/Scanner");

            buf_FieldId = env->GetFieldID(Class, "buf", "Ljava/nio/CharBuffer;");
            BUFFER_SIZE_FieldId = env->GetStaticFieldID(Class, "BUFFER_SIZE", "I");
            position_FieldId = env->GetFieldID(Class, "position", "I");
            matcher_FieldId = env->GetFieldID(Class, "matcher", "Ljava/util/regex/Matcher;");
            delimPattern_FieldId = env->GetFieldID(Class, "delimPattern", "Ljava/util/regex/Pattern;");
            hasNextPattern_FieldId = env->GetFieldID(Class, "hasNextPattern", "Ljava/util/regex/Pattern;");
            hasNextPosition_FieldId = env->GetFieldID(Class, "hasNextPosition", "I");
            hasNextResult_FieldId = env->GetFieldID(Class, "hasNextResult", "Ljava/lang/String;");
            source_FieldId = env->GetFieldID(Class, "source", "Ljava/lang/Readable;");
            sourceClosed_FieldId = env->GetFieldID(Class, "sourceClosed", "Z");
            needInput_FieldId = env->GetFieldID(Class, "needInput", "Z");
            skipped_FieldId = env->GetFieldID(Class, "skipped", "Z");
            savedScannerPosition_FieldId = env->GetFieldID(Class, "savedScannerPosition", "I");
            typeCache_FieldId = env->GetFieldID(Class, "typeCache", "Ljava/lang/Object;");
            matchValid_FieldId = env->GetFieldID(Class, "matchValid", "Z");
            closed_FieldId = env->GetFieldID(Class, "closed", "Z");
            radix_FieldId = env->GetFieldID(Class, "radix", "I");
            defaultRadix_FieldId = env->GetFieldID(Class, "defaultRadix", "I");
            locale_FieldId = env->GetFieldID(Class, "locale", "Ljava/util/Locale;");
            patternCache_FieldId = env->GetFieldID(Class, "patternCache", "Ljava/util/Scanner$PatternLRUCache;");
            lastException_FieldId = env->GetFieldID(Class, "lastException", "Ljava/io/IOException;");
            modCount_FieldId = env->GetFieldID(Class, "modCount", "I");
            WHITESPACE_PATTERN_FieldId = env->GetStaticFieldID(Class, "WHITESPACE_PATTERN", "Ljava/util/regex/Pattern;");
            FIND_ANY_PATTERN_FieldId = env->GetStaticFieldID(Class, "FIND_ANY_PATTERN", "Ljava/util/regex/Pattern;");
            NON_ASCII_DIGIT_FieldId = env->GetStaticFieldID(Class, "NON_ASCII_DIGIT", "Ljava/util/regex/Pattern;");
            groupSeparator_FieldId = env->GetFieldID(Class, "groupSeparator", "Ljava/lang/String;");
            decimalSeparator_FieldId = env->GetFieldID(Class, "decimalSeparator", "Ljava/lang/String;");
            nanString_FieldId = env->GetFieldID(Class, "nanString", "Ljava/lang/String;");
            infinityString_FieldId = env->GetFieldID(Class, "infinityString", "Ljava/lang/String;");
            positivePrefix_FieldId = env->GetFieldID(Class, "positivePrefix", "Ljava/lang/String;");
            negativePrefix_FieldId = env->GetFieldID(Class, "negativePrefix", "Ljava/lang/String;");
            positiveSuffix_FieldId = env->GetFieldID(Class, "positiveSuffix", "Ljava/lang/String;");
            negativeSuffix_FieldId = env->GetFieldID(Class, "negativeSuffix", "Ljava/lang/String;");
            boolPattern_FieldId = env->GetStaticFieldID(Class, "boolPattern", "Ljava/util/regex/Pattern;");
            BOOLEAN_PATTERN_FieldId = env->GetStaticFieldID(Class, "BOOLEAN_PATTERN", "Ljava/lang/String;");
            integerPattern_FieldId = env->GetFieldID(Class, "integerPattern", "Ljava/util/regex/Pattern;");
            digits_FieldId = env->GetStaticFieldID(Class, "digits", "Ljava/lang/String;");
            non0Digit_FieldId = env->GetStaticFieldID(Class, "non0Digit", "Ljava/lang/String;");
            SIMPLE_GROUP_INDEX_FieldId = env->GetStaticFieldID(Class, "SIMPLE_GROUP_INDEX", "I");
            separatorPattern_FieldId = env->GetStaticFieldID(Class, "separatorPattern", "Ljava/util/regex/Pattern;");
            linePattern_FieldId = env->GetStaticFieldID(Class, "linePattern", "Ljava/util/regex/Pattern;");
            LINE_SEPARATOR_PATTERN_FieldId = env->GetStaticFieldID(Class, "LINE_SEPARATOR_PATTERN", "Ljava/lang/String;");
            LINE_PATTERN_FieldId = env->GetStaticFieldID(Class, "LINE_PATTERN", "Ljava/lang/String;");
            floatPattern_FieldId = env->GetFieldID(Class, "floatPattern", "Ljava/util/regex/Pattern;");
            decimalPattern_FieldId = env->GetFieldID(Class, "decimalPattern", "Ljava/util/regex/Pattern;");
            _assertionsDisabled_FieldId = env->GetStaticFieldID(Class, "$assertionsDisabled", "Z");

            boolPattern_MethodId = env->GetStaticMethodID(Class, "boolPattern", "()Ljava/util/regex/Pattern;");
            buildIntegerPatternString_MethodId = env->GetMethodID(Class, "buildIntegerPatternString", "()Ljava/lang/String;");
            integerPattern_MethodId = env->GetMethodID(Class, "integerPattern", "()Ljava/util/regex/Pattern;");
            separatorPattern_MethodId = env->GetStaticMethodID(Class, "separatorPattern", "()Ljava/util/regex/Pattern;");
            linePattern_MethodId = env->GetStaticMethodID(Class, "linePattern", "()Ljava/util/regex/Pattern;");
            buildFloatAndDecimalPattern_MethodId = env->GetMethodID(Class, "buildFloatAndDecimalPattern", "()V");
            floatPattern_MethodId = env->GetMethodID(Class, "floatPattern", "()Ljava/util/regex/Pattern;");
            decimalPattern_MethodId = env->GetMethodID(Class, "decimalPattern", "()Ljava/util/regex/Pattern;");
            Scanner0_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/lang/Readable;Ljava/util/regex/Pattern;)V");
            Scanner1_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/lang/Readable;)V");
            Scanner2_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/InputStream;)V");
            Scanner3_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/InputStream;Ljava/lang/String;)V");
            Scanner4_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/InputStream;Ljava/nio/charset/Charset;)V");
            Scanner5_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/File;)V");
            Scanner6_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/File;Ljava/lang/String;)V");
            Scanner7_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/File;Ljava/nio/charset/Charset;)V");
            Scanner8_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/File;Ljava/nio/charset/CharsetDecoder;)V");
            Scanner9_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/nio/file/Path;)V");
            Scanner10_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/nio/file/Path;Ljava/lang/String;)V");
            Scanner11_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/nio/file/Path;Ljava/nio/charset/Charset;)V");
            Scanner12_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/lang/String;)V");
            Scanner13_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/nio/channels/ReadableByteChannel;)V");
            Scanner14_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/nio/channels/ReadableByteChannel;Ljava/lang/String;)V");
            Scanner15_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/charset/Charset;)V");
            toCharset_MethodId = env->GetStaticMethodID(Class, "toCharset", "(Ljava/lang/String;)Ljava/nio/charset/Charset;");
            makeReadable0_MethodId = env->GetStaticMethodID(Class, "makeReadable", "(Ljava/nio/file/Path;Ljava/nio/charset/Charset;)Ljava/lang/Readable;");
            makeReadable1_MethodId = env->GetStaticMethodID(Class, "makeReadable", "(Ljava/io/InputStream;Ljava/nio/charset/Charset;)Ljava/lang/Readable;");
            makeReadable2_MethodId = env->GetStaticMethodID(Class, "makeReadable", "(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/charset/CharsetDecoder;)Ljava/lang/Readable;");
            makeReadable3_MethodId = env->GetStaticMethodID(Class, "makeReadable", "(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/charset/Charset;)Ljava/lang/Readable;");
            makeReadable4_MethodId = env->GetStaticMethodID(Class, "makeReadable", "(Ljava/nio/channels/ReadableByteChannel;)Ljava/lang/Readable;");
            toDecoder_MethodId = env->GetStaticMethodID(Class, "toDecoder", "(Ljava/lang/String;)Ljava/nio/charset/CharsetDecoder;");
            saveState_MethodId = env->GetMethodID(Class, "saveState", "()V");
            revertState0_MethodId = env->GetMethodID(Class, "revertState", "()V");
            revertState1_MethodId = env->GetMethodID(Class, "revertState", "(Z)Z");
            cacheResult0_MethodId = env->GetMethodID(Class, "cacheResult", "()V");
            cacheResult1_MethodId = env->GetMethodID(Class, "cacheResult", "(Ljava/lang/String;)V");
            clearCaches_MethodId = env->GetMethodID(Class, "clearCaches", "()V");
            getCachedResult_MethodId = env->GetMethodID(Class, "getCachedResult", "()Ljava/lang/String;");
            useTypeCache_MethodId = env->GetMethodID(Class, "useTypeCache", "()V");
            readInput_MethodId = env->GetMethodID(Class, "readInput", "()V");
            makeSpace_MethodId = env->GetMethodID(Class, "makeSpace", "()Z");
            translateSavedIndexes_MethodId = env->GetMethodID(Class, "translateSavedIndexes", "(I)V");
            throwFor_MethodId = env->GetMethodID(Class, "throwFor", "()V");
            hasTokenInBuffer_MethodId = env->GetMethodID(Class, "hasTokenInBuffer", "()Z");
            getCompleteTokenInBuffer_MethodId = env->GetMethodID(Class, "getCompleteTokenInBuffer", "(Ljava/util/regex/Pattern;)Ljava/lang/String;");
            findPatternInBuffer_MethodId = env->GetMethodID(Class, "findPatternInBuffer", "(Ljava/util/regex/Pattern;I)Z");
            matchPatternInBuffer_MethodId = env->GetMethodID(Class, "matchPatternInBuffer", "(Ljava/util/regex/Pattern;)Z");
            ensureOpen_MethodId = env->GetMethodID(Class, "ensureOpen", "()V");
            close_MethodId = env->GetMethodID(Class, "close", "()V");
            ioException_MethodId = env->GetMethodID(Class, "ioException", "()Ljava/io/IOException;");
            delimiter_MethodId = env->GetMethodID(Class, "delimiter", "()Ljava/util/regex/Pattern;");
            useDelimiter0_MethodId = env->GetMethodID(Class, "useDelimiter", "(Ljava/util/regex/Pattern;)Ljava/util/Scanner;");
            useDelimiter1_MethodId = env->GetMethodID(Class, "useDelimiter", "(Ljava/lang/String;)Ljava/util/Scanner;");
            locale_MethodId = env->GetMethodID(Class, "locale", "()Ljava/util/Locale;");
            useLocale_MethodId = env->GetMethodID(Class, "useLocale", "(Ljava/util/Locale;)Ljava/util/Scanner;");
            radix_MethodId = env->GetMethodID(Class, "radix", "()I");
            useRadix_MethodId = env->GetMethodID(Class, "useRadix", "(I)Ljava/util/Scanner;");
            setRadix_MethodId = env->GetMethodID(Class, "setRadix", "(I)V");
            match_MethodId = env->GetMethodID(Class, "match", "()Ljava/util/regex/MatchResult;");
            toString_MethodId = env->GetMethodID(Class, "toString", "()Ljava/lang/String;");
            hasNext0_MethodId = env->GetMethodID(Class, "hasNext", "()Z");
            hasNext1_MethodId = env->GetMethodID(Class, "hasNext", "(Ljava/lang/String;)Z");
            hasNext2_MethodId = env->GetMethodID(Class, "hasNext", "(Ljava/util/regex/Pattern;)Z");
            next0_MethodId = env->GetMethodID(Class, "next", "()Ljava/lang/String;");
            next1_MethodId = env->GetMethodID(Class, "next", "(Ljava/lang/String;)Ljava/lang/String;");
            next2_MethodId = env->GetMethodID(Class, "next", "(Ljava/util/regex/Pattern;)Ljava/lang/String;");
            next3_MethodId = env->GetMethodID(Class, "next", "()Ljava/lang/Object;");
            remove_MethodId = env->GetMethodID(Class, "remove", "()V");
            hasNextLine_MethodId = env->GetMethodID(Class, "hasNextLine", "()Z");
            nextLine_MethodId = env->GetMethodID(Class, "nextLine", "()Ljava/lang/String;");
            findInLine0_MethodId = env->GetMethodID(Class, "findInLine", "(Ljava/lang/String;)Ljava/lang/String;");
            findInLine1_MethodId = env->GetMethodID(Class, "findInLine", "(Ljava/util/regex/Pattern;)Ljava/lang/String;");
            findWithinHorizon0_MethodId = env->GetMethodID(Class, "findWithinHorizon", "(Ljava/lang/String;I)Ljava/lang/String;");
            findWithinHorizon1_MethodId = env->GetMethodID(Class, "findWithinHorizon", "(Ljava/util/regex/Pattern;I)Ljava/lang/String;");
            skip0_MethodId = env->GetMethodID(Class, "skip", "(Ljava/util/regex/Pattern;)Ljava/util/Scanner;");
            skip1_MethodId = env->GetMethodID(Class, "skip", "(Ljava/lang/String;)Ljava/util/Scanner;");
            hasNextBoolean_MethodId = env->GetMethodID(Class, "hasNextBoolean", "()Z");
            nextBoolean_MethodId = env->GetMethodID(Class, "nextBoolean", "()Z");
            hasNextByte0_MethodId = env->GetMethodID(Class, "hasNextByte", "()Z");
            hasNextByte1_MethodId = env->GetMethodID(Class, "hasNextByte", "(I)Z");
            nextByte0_MethodId = env->GetMethodID(Class, "nextByte", "()B");
            nextByte1_MethodId = env->GetMethodID(Class, "nextByte", "(I)B");
            hasNextShort0_MethodId = env->GetMethodID(Class, "hasNextShort", "()Z");
            hasNextShort1_MethodId = env->GetMethodID(Class, "hasNextShort", "(I)Z");
            nextShort0_MethodId = env->GetMethodID(Class, "nextShort", "()S");
            nextShort1_MethodId = env->GetMethodID(Class, "nextShort", "(I)S");
            hasNextInt0_MethodId = env->GetMethodID(Class, "hasNextInt", "()Z");
            hasNextInt1_MethodId = env->GetMethodID(Class, "hasNextInt", "(I)Z");
            processIntegerToken_MethodId = env->GetMethodID(Class, "processIntegerToken", "(Ljava/lang/String;)Ljava/lang/String;");
            nextInt0_MethodId = env->GetMethodID(Class, "nextInt", "()I");
            nextInt1_MethodId = env->GetMethodID(Class, "nextInt", "(I)I");
            hasNextLong0_MethodId = env->GetMethodID(Class, "hasNextLong", "()Z");
            hasNextLong1_MethodId = env->GetMethodID(Class, "hasNextLong", "(I)Z");
            nextLong0_MethodId = env->GetMethodID(Class, "nextLong", "()J");
            nextLong1_MethodId = env->GetMethodID(Class, "nextLong", "(I)J");
            processFloatToken_MethodId = env->GetMethodID(Class, "processFloatToken", "(Ljava/lang/String;)Ljava/lang/String;");
            hasNextFloat_MethodId = env->GetMethodID(Class, "hasNextFloat", "()Z");
            nextFloat_MethodId = env->GetMethodID(Class, "nextFloat", "()F");
            hasNextDouble_MethodId = env->GetMethodID(Class, "hasNextDouble", "()Z");
            nextDouble_MethodId = env->GetMethodID(Class, "nextDouble", "()D");
            hasNextBigInteger0_MethodId = env->GetMethodID(Class, "hasNextBigInteger", "()Z");
            hasNextBigInteger1_MethodId = env->GetMethodID(Class, "hasNextBigInteger", "(I)Z");
            nextBigInteger0_MethodId = env->GetMethodID(Class, "nextBigInteger", "()Ljava/math/BigInteger;");
            nextBigInteger1_MethodId = env->GetMethodID(Class, "nextBigInteger", "(I)Ljava/math/BigInteger;");
            hasNextBigDecimal_MethodId = env->GetMethodID(Class, "hasNextBigDecimal", "()Z");
            nextBigDecimal_MethodId = env->GetMethodID(Class, "nextBigDecimal", "()Ljava/math/BigDecimal;");
            reset_MethodId = env->GetMethodID(Class, "reset", "()Ljava/util/Scanner;");
            tokens_MethodId = env->GetMethodID(Class, "tokens", "()Ljava/util/stream/Stream;");
            findAll0_MethodId = env->GetMethodID(Class, "findAll", "(Ljava/util/regex/Pattern;)Ljava/util/stream/Stream;");
            findAll1_MethodId = env->GetMethodID(Class, "findAll", "(Ljava/lang/String;)Ljava/util/stream/Stream;");

            initialized = true;
        }
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.nio.CharBuffer</returns>
    public JObject* GetBuf()
    {
        var result = _env->GetObjectField(Object, buf_FieldId);
        return result;
    }
    public static int GetBUFFER_SIZE(JniEnv* env)
    {
        var result = env->GetStaticIntField(Class, BUFFER_SIZE_FieldId);
        return result;
    }
    public int GetPosition()
    {
        var result = _env->GetIntField(Object, position_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Matcher</returns>
    public JObject* GetMatcher()
    {
        var result = _env->GetObjectField(Object, matcher_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* GetDelimPattern()
    {
        var result = _env->GetObjectField(Object, delimPattern_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* GetHasNextPattern()
    {
        var result = _env->GetObjectField(Object, hasNextPattern_FieldId);
        return result;
    }
    public int GetHasNextPosition()
    {
        var result = _env->GetIntField(Object, hasNextPosition_FieldId);
        return result;
    }
    public string GetHasNextResult()
    {
        var result = _env->GetObjectField(Object, hasNextResult_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.Readable</returns>
    public JObject* GetSource()
    {
        var result = _env->GetObjectField(Object, source_FieldId);
        return result;
    }
    public bool GetSourceClosed()
    {
        var result = _env->GetBooleanField(Object, sourceClosed_FieldId);
        return result;
    }
    public bool GetNeedInput()
    {
        var result = _env->GetBooleanField(Object, needInput_FieldId);
        return result;
    }
    public bool GetSkipped()
    {
        var result = _env->GetBooleanField(Object, skipped_FieldId);
        return result;
    }
    public int GetSavedScannerPosition()
    {
        var result = _env->GetIntField(Object, savedScannerPosition_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.Object</returns>
    public JObject* GetTypeCache()
    {
        var result = _env->GetObjectField(Object, typeCache_FieldId);
        return result;
    }
    public bool GetMatchValid()
    {
        var result = _env->GetBooleanField(Object, matchValid_FieldId);
        return result;
    }
    public bool GetClosed()
    {
        var result = _env->GetBooleanField(Object, closed_FieldId);
        return result;
    }
    public int GetRadix()
    {
        var result = _env->GetIntField(Object, radix_FieldId);
        return result;
    }
    public int GetDefaultRadix()
    {
        var result = _env->GetIntField(Object, defaultRadix_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Locale</returns>
    public JObject* GetLocale()
    {
        var result = _env->GetObjectField(Object, locale_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Scanner$PatternLRUCache</returns>
    public JObject* GetPatternCache()
    {
        var result = _env->GetObjectField(Object, patternCache_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.IOException</returns>
    public JObject* GetLastException()
    {
        var result = _env->GetObjectField(Object, lastException_FieldId);
        return result;
    }
    public int GetModCount()
    {
        var result = _env->GetIntField(Object, modCount_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* GetWHITESPACE_PATTERN(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, WHITESPACE_PATTERN_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* GetFIND_ANY_PATTERN(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, FIND_ANY_PATTERN_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* GetNON_ASCII_DIGIT(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, NON_ASCII_DIGIT_FieldId);
        return result;
    }
    public string GetGroupSeparator()
    {
        var result = _env->GetObjectField(Object, groupSeparator_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    public string GetDecimalSeparator()
    {
        var result = _env->GetObjectField(Object, decimalSeparator_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    public string GetNanString()
    {
        var result = _env->GetObjectField(Object, nanString_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    public string GetInfinityString()
    {
        var result = _env->GetObjectField(Object, infinityString_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    public string GetPositivePrefix()
    {
        var result = _env->GetObjectField(Object, positivePrefix_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    public string GetNegativePrefix()
    {
        var result = _env->GetObjectField(Object, negativePrefix_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    public string GetPositiveSuffix()
    {
        var result = _env->GetObjectField(Object, positiveSuffix_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    public string GetNegativeSuffix()
    {
        var result = _env->GetObjectField(Object, negativeSuffix_FieldId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* GetBoolPattern(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, boolPattern_FieldId);
        return result;
    }
    public static string GetBOOLEAN_PATTERN(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, BOOLEAN_PATTERN_FieldId);
        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* GetIntegerPattern()
    {
        var result = _env->GetObjectField(Object, integerPattern_FieldId);
        return result;
    }
    public static string GetDigits(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, digits_FieldId);
        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    public static string GetNon0Digit(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, non0Digit_FieldId);
        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    public static int GetSIMPLE_GROUP_INDEX(JniEnv* env)
    {
        var result = env->GetStaticIntField(Class, SIMPLE_GROUP_INDEX_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* GetSeparatorPattern(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, separatorPattern_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* GetLinePattern(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, linePattern_FieldId);
        return result;
    }
    public static string GetLINE_SEPARATOR_PATTERN(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, LINE_SEPARATOR_PATTERN_FieldId);
        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    public static string GetLINE_PATTERN(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, LINE_PATTERN_FieldId);
        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* GetFloatPattern()
    {
        var result = _env->GetObjectField(Object, floatPattern_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* GetDecimalPattern()
    {
        var result = _env->GetObjectField(Object, decimalPattern_FieldId);
        return result;
    }
    public static bool Get_assertionsDisabled(JniEnv* env)
    {
        var result = env->GetStaticBooleanField(Class, _assertionsDisabled_FieldId);
        return result;
    }

    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.nio.CharBuffer</param>
    
    public void SetBuf(JObject* value)
    {
        _env->SetObjectField(Object, buf_FieldId, value);
    }
    public static void SetBUFFER_SIZE(JniEnv* env, int value)
    {
        env->SetStaticIntField(Class, BUFFER_SIZE_FieldId, value);
    }
    public void SetPosition(int value)
    {
        _env->SetIntField(Object, position_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Matcher</param>
    
    public void SetMatcher(JObject* value)
    {
        _env->SetObjectField(Object, matcher_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public void SetDelimPattern(JObject* value)
    {
        _env->SetObjectField(Object, delimPattern_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public void SetHasNextPattern(JObject* value)
    {
        _env->SetObjectField(Object, hasNextPattern_FieldId, value);
    }
    public void SetHasNextPosition(int value)
    {
        _env->SetIntField(Object, hasNextPosition_FieldId, value);
    }
    public void SetHasNextResult(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, hasNextResult_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.lang.Readable</param>
    
    public void SetSource(JObject* value)
    {
        _env->SetObjectField(Object, source_FieldId, value);
    }
    public void SetSourceClosed(bool value)
    {
        _env->SetBooleanField(Object, sourceClosed_FieldId, value);
    }
    public void SetNeedInput(bool value)
    {
        _env->SetBooleanField(Object, needInput_FieldId, value);
    }
    public void SetSkipped(bool value)
    {
        _env->SetBooleanField(Object, skipped_FieldId, value);
    }
    public void SetSavedScannerPosition(int value)
    {
        _env->SetIntField(Object, savedScannerPosition_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.lang.Object</param>
    
    public void SetTypeCache(JObject* value)
    {
        _env->SetObjectField(Object, typeCache_FieldId, value);
    }
    public void SetMatchValid(bool value)
    {
        _env->SetBooleanField(Object, matchValid_FieldId, value);
    }
    public void SetClosed(bool value)
    {
        _env->SetBooleanField(Object, closed_FieldId, value);
    }
    public void SetDefaultRadix(int value)
    {
        _env->SetIntField(Object, defaultRadix_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.Locale</param>
    
    public void SetLocale(JObject* value)
    {
        _env->SetObjectField(Object, locale_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.Scanner$PatternLRUCache</param>
    
    public void SetPatternCache(JObject* value)
    {
        _env->SetObjectField(Object, patternCache_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.io.IOException</param>
    
    public void SetLastException(JObject* value)
    {
        _env->SetObjectField(Object, lastException_FieldId, value);
    }
    public void SetModCount(int value)
    {
        _env->SetIntField(Object, modCount_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public static void SetWHITESPACE_PATTERN(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, WHITESPACE_PATTERN_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public static void SetFIND_ANY_PATTERN(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, FIND_ANY_PATTERN_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public static void SetNON_ASCII_DIGIT(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, NON_ASCII_DIGIT_FieldId, value);
    }
    public void SetGroupSeparator(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, groupSeparator_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    public void SetDecimalSeparator(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, decimalSeparator_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    public void SetNanString(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, nanString_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    public void SetInfinityString(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, infinityString_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    public void SetPositivePrefix(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, positivePrefix_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    public void SetNegativePrefix(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, negativePrefix_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    public void SetPositiveSuffix(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, positiveSuffix_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    public void SetNegativeSuffix(string value)
    {
        JObject* stringValue = (JObject*)_env->NewStringUTF(value);
        _env->SetObjectField(Object, negativeSuffix_FieldId, stringValue);
        _env->DeleteLocalRef(stringValue);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public static void SetBoolPattern(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, boolPattern_FieldId, value);
    }
    public static void SetBOOLEAN_PATTERN(JniEnv* env, string value)
    {
        JObject* stringValue = (JObject*)env->NewStringUTF(value);
        env->SetStaticObjectField(Class, BOOLEAN_PATTERN_FieldId, stringValue);
        env->DeleteLocalRef(stringValue);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public void SetIntegerPattern(JObject* value)
    {
        _env->SetObjectField(Object, integerPattern_FieldId, value);
    }
    public static void SetDigits(JniEnv* env, string value)
    {
        JObject* stringValue = (JObject*)env->NewStringUTF(value);
        env->SetStaticObjectField(Class, digits_FieldId, stringValue);
        env->DeleteLocalRef(stringValue);
    }
    public static void SetNon0Digit(JniEnv* env, string value)
    {
        JObject* stringValue = (JObject*)env->NewStringUTF(value);
        env->SetStaticObjectField(Class, non0Digit_FieldId, stringValue);
        env->DeleteLocalRef(stringValue);
    }
    public static void SetSIMPLE_GROUP_INDEX(JniEnv* env, int value)
    {
        env->SetStaticIntField(Class, SIMPLE_GROUP_INDEX_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public static void SetSeparatorPattern(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, separatorPattern_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public static void SetLinePattern(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, linePattern_FieldId, value);
    }
    public static void SetLINE_SEPARATOR_PATTERN(JniEnv* env, string value)
    {
        JObject* stringValue = (JObject*)env->NewStringUTF(value);
        env->SetStaticObjectField(Class, LINE_SEPARATOR_PATTERN_FieldId, stringValue);
        env->DeleteLocalRef(stringValue);
    }
    public static void SetLINE_PATTERN(JniEnv* env, string value)
    {
        JObject* stringValue = (JObject*)env->NewStringUTF(value);
        env->SetStaticObjectField(Class, LINE_PATTERN_FieldId, stringValue);
        env->DeleteLocalRef(stringValue);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public void SetFloatPattern(JObject* value)
    {
        _env->SetObjectField(Object, floatPattern_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.regex.Pattern</param>
    
    public void SetDecimalPattern(JObject* value)
    {
        _env->SetObjectField(Object, decimalPattern_FieldId, value);
    }
    public static void Set_assertionsDisabled(JniEnv* env, bool value)
    {
        env->SetStaticBooleanField(Class, _assertionsDisabled_FieldId, value);
    }

    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.Readable</param>
    /// <param name="arg1">java.util.regex.Pattern</param>
    public static Scanner Scanner0_Constructor(JniEnv* env, JObject* arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].L = arg1;

        var result = env->NewObjectA(Class, Scanner0_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.Readable</param>
    public static Scanner Scanner1_Constructor(JniEnv* env, JObject* arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = env->NewObjectA(Class, Scanner1_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.InputStream</param>
    public static Scanner Scanner2_Constructor(JniEnv* env, InputStream arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0.Object;

        var result = env->NewObjectA(Class, Scanner2_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.InputStream</param>
    /// <param name="arg1">java.lang.String</param>
    public static Scanner Scanner3_Constructor(JniEnv* env, JObject* arg0, string arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->NewObjectA(Class, Scanner3_MethodId, args);
        env->DeleteLocalRef(stringArg1);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.InputStream</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    public static Scanner Scanner4_Constructor(JniEnv* env, JObject* arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].L = arg1;

        var result = env->NewObjectA(Class, Scanner4_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.File</param>
    public static Scanner Scanner5_Constructor(JniEnv* env, JObject* arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = env->NewObjectA(Class, Scanner5_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.File</param>
    /// <param name="arg1">java.lang.String</param>
    public static Scanner Scanner6_Constructor(JniEnv* env, JObject* arg0, string arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->NewObjectA(Class, Scanner6_MethodId, args);
        env->DeleteLocalRef(stringArg1);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.File</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    public static Scanner Scanner7_Constructor(JniEnv* env, JObject* arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].L = arg1;

        var result = env->NewObjectA(Class, Scanner7_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.File</param>
    /// <param name="arg1">java.nio.charset.CharsetDecoder</param>
    public static Scanner Scanner8_Constructor(JniEnv* env, JObject* arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].L = arg1;

        var result = env->NewObjectA(Class, Scanner8_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.file.Path</param>
    public static Scanner Scanner9_Constructor(JniEnv* env, JObject* arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = env->NewObjectA(Class, Scanner9_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.file.Path</param>
    /// <param name="arg1">java.lang.String</param>
    public static Scanner Scanner10_Constructor(JniEnv* env, JObject* arg0, string arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->NewObjectA(Class, Scanner10_MethodId, args);
        env->DeleteLocalRef(stringArg1);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.file.Path</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    public static Scanner Scanner11_Constructor(JniEnv* env, JObject* arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].L = arg1;

        var result = env->NewObjectA(Class, Scanner11_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    public static Scanner Scanner12_Constructor(JniEnv* env, string arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->NewObjectA(Class, Scanner12_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.channels.ReadableByteChannel</param>
    public static Scanner Scanner13_Constructor(JniEnv* env, JObject* arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = env->NewObjectA(Class, Scanner13_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.channels.ReadableByteChannel</param>
    /// <param name="arg1">java.lang.String</param>
    public static Scanner Scanner14_Constructor(JniEnv* env, JObject* arg0, string arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->NewObjectA(Class, Scanner14_MethodId, args);
        env->DeleteLocalRef(stringArg1);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.channels.ReadableByteChannel</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    public static Scanner Scanner15_Constructor(JniEnv* env, JObject* arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].L = arg1;

        var result = env->NewObjectA(Class, Scanner15_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* BoolPattern(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, boolPattern_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.String</returns>
    public string BuildIntegerPatternString()
    {
        var result = _env->CallObjectMethod(Object, buildIntegerPatternString_MethodId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* IntegerPattern()
    {
        var result = _env->CallObjectMethod(Object, integerPattern_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* SeparatorPattern(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, separatorPattern_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public static JObject* LinePattern(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, linePattern_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void BuildFloatAndDecimalPattern()
    {
        _env->CallVoidMethod(Object, buildFloatAndDecimalPattern_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* FloatPattern()
    {
        var result = _env->CallObjectMethod(Object, floatPattern_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* DecimalPattern()
    {
        var result = _env->CallObjectMethod(Object, decimalPattern_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.nio.charset.Charset</returns>
    public static JObject* ToCharset(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->CallStaticObjectMethodA(Class, toCharset_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.file.Path</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    /// <returns>java.lang.Readable</returns>
    public static JObject* MakeReadable(JniEnv* env, JObject* arg0, JObject* arg1)
    {
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].L = arg1;

        var result = env->CallStaticObjectMethodA(Class, makeReadable0_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.InputStream</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    /// <returns>java.lang.Readable</returns>
    //public static JObject* MakeReadable(JniEnv* env, JObject* arg0, JObject* arg1)
    //{
    //    JValue* args = stackalloc JValue[2];
    //    args[0].L = arg0;
    //    args[1].L = arg1;

    //    var result = env->CallStaticObjectMethodA(Class, makeReadable1_MethodId, args);
    //    return result;
    //}
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.channels.ReadableByteChannel</param>
    /// <param name="arg1">java.nio.charset.CharsetDecoder</param>
    /// <returns>java.lang.Readable</returns>
    //public static JObject* MakeReadable(JniEnv* env, JObject* arg0, JObject* arg1)
    //{
    //    JValue* args = stackalloc JValue[2];
    //    args[0].L = arg0;
    //    args[1].L = arg1;

    //    var result = env->CallStaticObjectMethodA(Class, makeReadable2_MethodId, args);
    //    return result;
    //}
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.channels.ReadableByteChannel</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    /// <returns>java.lang.Readable</returns>
    //public static JObject* MakeReadable(JniEnv* env, JObject* arg0, JObject* arg1)
    //{
    //    JValue* args = stackalloc JValue[2];
    //    args[0].L = arg0;
    //    args[1].L = arg1;

    //    var result = env->CallStaticObjectMethodA(Class, makeReadable3_MethodId, args);
    //    return result;
    //}
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.nio.channels.ReadableByteChannel</param>
    /// <returns>java.lang.Readable</returns>
    public static JObject* MakeReadable(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = env->CallStaticObjectMethodA(Class, makeReadable4_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.nio.charset.CharsetDecoder</returns>
    public static JObject* ToDecoder(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->CallStaticObjectMethodA(Class, toDecoder_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void SaveState()
    {
        _env->CallVoidMethod(Object, saveState_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void RevertState()
    {
        _env->CallVoidMethod(Object, revertState0_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool RevertState(bool arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].Z = (byte)(arg0 ? 1 : 0);

        var result = _env->CallBooleanMethodA(Object, revertState1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void CacheResult()
    {
        _env->CallVoidMethod(Object, cacheResult0_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>void</returns>
    public void CacheResult(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        _env->CallVoidMethodA(Object, cacheResult1_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void ClearCaches()
    {
        _env->CallVoidMethod(Object, clearCaches_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.String</returns>
    public string GetCachedResult()
    {
        var result = _env->CallObjectMethod(Object, getCachedResult_MethodId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void UseTypeCache()
    {
        _env->CallVoidMethod(Object, useTypeCache_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void ReadInput()
    {
        _env->CallVoidMethod(Object, readInput_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool MakeSpace()
    {
        var result = _env->CallBooleanMethod(Object, makeSpace_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void TranslateSavedIndexes(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        _env->CallVoidMethodA(Object, translateSavedIndexes_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void ThrowFor()
    {
        _env->CallVoidMethod(Object, throwFor_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasTokenInBuffer()
    {
        var result = _env->CallBooleanMethod(Object, hasTokenInBuffer_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>java.lang.String</returns>
    public string GetCompleteTokenInBuffer(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallObjectMethodA(Object, getCompleteTokenInBuffer_MethodId, args);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>boolean</returns>
    public bool FindPatternInBuffer(JObject* arg0, int arg1)
    {
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].I = arg1;

        var result = _env->CallBooleanMethodA(Object, findPatternInBuffer_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>boolean</returns>
    public bool MatchPatternInBuffer(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallBooleanMethodA(Object, matchPatternInBuffer_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void EnsureOpen()
    {
        _env->CallVoidMethod(Object, ensureOpen_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Close()
    {
        _env->CallVoidMethod(Object, close_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.IOException</returns>
    public JObject* IoException()
    {
        var result = _env->CallObjectMethod(Object, ioException_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.Pattern</returns>
    public JObject* Delimiter()
    {
        var result = _env->CallObjectMethod(Object, delimiter_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>java.util.Scanner</returns>
    public JObject* UseDelimiter(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallObjectMethodA(Object, useDelimiter0_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.util.Scanner</returns>
    public JObject* UseDelimiter(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = _env->CallObjectMethodA(Object, useDelimiter1_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Locale</returns>
    public JObject* Locale()
    {
        var result = _env->CallObjectMethod(Object, locale_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.Locale</param>
    /// <returns>java.util.Scanner</returns>
    public JObject* UseLocale(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallObjectMethodA(Object, useLocale_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>int</returns>
    public int Radix()
    {
        var result = _env->CallIntMethod(Object, radix_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Scanner</returns>
    public JObject* UseRadix(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallObjectMethodA(Object, useRadix_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void SetRadix(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        _env->CallVoidMethodA(Object, setRadix_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.regex.MatchResult</returns>
    public JObject* Match()
    {
        var result = _env->CallObjectMethod(Object, match_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.String</returns>
    public override string ToString()
    {
        var result = _env->CallObjectMethod(Object, toString_MethodId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNext()
    {
        var result = _env->CallBooleanMethod(Object, hasNext0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>boolean</returns>
    public bool HasNext(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = _env->CallBooleanMethodA(Object, hasNext1_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>boolean</returns>
    public bool HasNext(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallBooleanMethodA(Object, hasNext2_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.String</returns>
    public string Next()
    {
        var result = _env->CallObjectMethod(Object, next0_MethodId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public string Next(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = _env->CallObjectMethodA(Object, next1_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>java.lang.String</returns>
    public string Next(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallObjectMethodA(Object, next2_MethodId, args);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.Object</returns>
    //public JObject* Next()
    //{
    //    var result = _env->CallObjectMethod(Object, next3_MethodId);
    //    return result;
    //}
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Remove()
    {
        _env->CallVoidMethod(Object, remove_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextLine()
    {
        var result = _env->CallBooleanMethod(Object, hasNextLine_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.String</returns>
    public string NextLine()
    {
        var result = _env->CallObjectMethod(Object, nextLine_MethodId);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public string FindInLine(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = _env->CallObjectMethodA(Object, findInLine0_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>java.lang.String</returns>
    public string FindInLine(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallObjectMethodA(Object, findInLine1_MethodId, args);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public string FindWithinHorizon(string arg0, int arg1)
    {
        JValue* args = stackalloc JValue[2];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;
        args[1].I = arg1;

        var result = _env->CallObjectMethodA(Object, findWithinHorizon0_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>java.lang.String</returns>
    public string FindWithinHorizon(JObject* arg0, int arg1)
    {
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].I = arg1;

        var result = _env->CallObjectMethodA(Object, findWithinHorizon1_MethodId, args);
        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>java.util.Scanner</returns>
    public JObject* Skip(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallObjectMethodA(Object, skip0_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.util.Scanner</returns>
    public JObject* Skip(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = _env->CallObjectMethodA(Object, skip1_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextBoolean()
    {
        var result = _env->CallBooleanMethod(Object, hasNextBoolean_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool NextBoolean()
    {
        var result = _env->CallBooleanMethod(Object, nextBoolean_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextByte()
    {
        var result = _env->CallBooleanMethod(Object, hasNextByte0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextByte(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallBooleanMethodA(Object, hasNextByte1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>byte</returns>
    public sbyte NextByte()
    {
        var result = _env->CallByteMethod(Object, nextByte0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>byte</returns>
    public sbyte NextByte(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallByteMethodA(Object, nextByte1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextShort()
    {
        var result = _env->CallBooleanMethod(Object, hasNextShort0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextShort(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallBooleanMethodA(Object, hasNextShort1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>short</returns>
    public short NextShort()
    {
        var result = _env->CallShortMethod(Object, nextShort0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>short</returns>
    public short NextShort(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallShortMethodA(Object, nextShort1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextInt()
    {
        var result = _env->CallBooleanMethod(Object, hasNextInt0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextInt(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallBooleanMethodA(Object, hasNextInt1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public string ProcessIntegerToken(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = _env->CallObjectMethodA(Object, processIntegerToken_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>int</returns>
    public int NextInt()
    {
        var result = _env->CallIntMethod(Object, nextInt0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>int</returns>
    public int NextInt(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallIntMethodA(Object, nextInt1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextLong()
    {
        var result = _env->CallBooleanMethod(Object, hasNextLong0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextLong(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallBooleanMethodA(Object, hasNextLong1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>long</returns>
    public long NextLong()
    {
        var result = _env->CallLongMethod(Object, nextLong0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>long</returns>
    public long NextLong(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallLongMethodA(Object, nextLong1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public string ProcessFloatToken(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = _env->CallObjectMethodA(Object, processFloatToken_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        string stringResult = _env->JStringToString((JString*)result);
        _env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextFloat()
    {
        var result = _env->CallBooleanMethod(Object, hasNextFloat_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>float</returns>
    public float NextFloat()
    {
        var result = _env->CallFloatMethod(Object, nextFloat_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextDouble()
    {
        var result = _env->CallBooleanMethod(Object, hasNextDouble_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>double</returns>
    public double NextDouble()
    {
        var result = _env->CallDoubleMethod(Object, nextDouble_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextBigInteger()
    {
        var result = _env->CallBooleanMethod(Object, hasNextBigInteger0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextBigInteger(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallBooleanMethodA(Object, hasNextBigInteger1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.math.BigInteger</returns>
    public JObject* NextBigInteger()
    {
        var result = _env->CallObjectMethod(Object, nextBigInteger0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.math.BigInteger</returns>
    public JObject* NextBigInteger(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallObjectMethodA(Object, nextBigInteger1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool HasNextBigDecimal()
    {
        var result = _env->CallBooleanMethod(Object, hasNextBigDecimal_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.math.BigDecimal</returns>
    public JObject* NextBigDecimal()
    {
        var result = _env->CallObjectMethod(Object, nextBigDecimal_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Scanner</returns>
    public JObject* Reset()
    {
        var result = _env->CallObjectMethod(Object, reset_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.stream.Stream<java.lang.String></returns>
    public JObject* Tokens()
    {
        var result = _env->CallObjectMethod(Object, tokens_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.regex.Pattern</param>
    /// <returns>java.util.stream.Stream<java.util.regex.MatchResult></returns>
    public JObject* FindAll(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallObjectMethodA(Object, findAll0_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.util.stream.Stream<java.util.regex.MatchResult></returns>
    public JObject* FindAll(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = _env->CallObjectMethodA(Object, findAll1_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        return result;
    }
}