// <auto-generated />
using JavaNETInterface.Jni;
using JavaNETInterface.Wrappers;

namespace JniSharpGenerator.Sample;

public unsafe class JavaSample : JniObject
{
    public static JClass* Class { get; private set; }
    private static readonly Lock lockObject = new();
    private static bool initialized;

    private static JFieldID* value_FieldId;

    private static JMethodID* JavaSample_MethodId;
    private static JMethodID* main_MethodId;
    private static JMethodID* add_MethodId;
    private static JMethodID* nativeSharpMethod_MethodId;

    public JavaSample(JniEnv* env, JObject* obj) : base(env, obj)
        => Initialize(env);

    public static void Initialize(JniEnv* env)
    {
        lock(lockObject)
        {
            if(initialized)
                return;

            Class = env->FindClass("JniSharpGenerator/Sample/JavaSample");

            value_FieldId = env->GetStaticFieldID(Class, "value", "I");

            JavaSample_MethodId = env->GetMethodID(Class, "<init>", "()V");
            main_MethodId = env->GetStaticMethodID(Class, "main", "([Ljava/lang/String;)V");
            add_MethodId = env->GetStaticMethodID(Class, "add", "(II)I");
            nativeSharpMethod_MethodId = env->GetStaticMethodID(Class, "nativeSharpMethod", "()V");

            initialized = true;
        }
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>int</returns>
    public static int GetValue(JniEnv* env)
    {
        var result = env->GetStaticIntField(Class, value_FieldId);
        return result;
    }

    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">int</param>
    
    public static void SetValue(JniEnv* env, int value)
    {
        env->SetStaticIntField(Class, value_FieldId, value);
    }

    /// <summary>
    /// To be documented
    /// </summary>
    public static JavaSample JavaSample_Constructor(JniEnv* env)
    {
        Initialize(env);
        var result = env->NewObject(Class, JavaSample_MethodId);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String[]</param>
    /// <returns>void</returns>
    public static void Main(JniEnv* env, JObjectArray* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = (JObject*)arg0;

        env->CallStaticVoidMethodA(Class, main_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>int</returns>
    public static int Add(JniEnv* env, int arg0, int arg1)
    {
        JValue* args = stackalloc JValue[2];
        args[0].I = arg0;
        args[1].I = arg1;

        var result = env->CallStaticIntMethodA(Class, add_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public static void NativeSharpMethod(JniEnv* env)
    {
        env->CallStaticVoidMethod(Class, nativeSharpMethod_MethodId);
    }
}