using JniSharpGenerator.Parser;
using System.Text;
using System.Text.RegularExpressions;

namespace JniSharpGenerator
{
    internal static class Syntax
    {
        private static readonly string[] _primitives = ["byte", "short", "int", "long", "float", "double", "char", "boolean"];

        private static bool IsPrimitive(string type)
            => _primitives.Contains(type);

        private static string ConvertType(string type)
        {
            var groups = Regex.Match(type, Expressions.TypeSignature).Groups;
            string arrayType = groups["name"].Value;
            bool isArray = (groups["vararg"].Success || groups["dimensions"].Success);

            return type switch
            {
                "" => "void", // for constructors
                "void" => "void",
                "byte" => "byte",
                "short" => "short",
                "int" => "int",
                "long" => "long",
                "float" => "float",
                "double" => "double",
                "char" => "char",
                "boolean" => "bool",
                "java.lang.String" => "string",
                _ when isArray && IsPrimitive(arrayType) => $"J{FirstCharToUpper(arrayType)}Array*",
                _ when isArray => "JObjectArray*",
                _ => "JObject*"
            };
        }

        private static string GetJValueField(string type)
            => type switch
            {
                "byte" => "B",
                "bool" => "Z", // pre-conversion required
                "sbyte" => "B",
                "short" => "S",
                "ushort" => "C",
                "char" => "C",
                "int" => "I",
                "long" => "J",
                "float" => "F",
                "double" => "D",
                "void" => "V",
                _ => "L"
            };

        private static string? ConvertToDescriptor(string type)
        {
            if (string.IsNullOrWhiteSpace(type) || !type.IsMatch(Expressions.TypeSignature))
                return null;

            GroupCollection? groups = Regex.Match(type, Expressions.TypeSignature).Groups;

            string typeName = groups["name"].Value;

            string descriptor = typeName switch
            {
                "byte" => "B",
                "boolean" => "Z",
                "char" => "C",
                "short" => "S",
                "int" => "I",
                "long" => "J",
                "float" => "F",
                "double" => "D",
                "void" => "V",
                _ => $"L{typeName.Replace('.', '/')};"
            };

            int dimensionsCount = groups["vararg"].Success ? 1 : groups["dimensions"].Value.Count('[');

            if (dimensionsCount > 0)
                descriptor = $"{new string('[', dimensionsCount)}{descriptor}";

            return descriptor;
        }

        public static string GetSharpClassDefinition(JavaClass klass, bool generateAccessors = false)
        {
            StringBuilder klassBuilder = new();
            List<MethodData> methodDatas = GroupMethodOverloads(klass.Methods!);
            string cleanedName = klass.Name.Replace("$", "_");

            // Header
            klassBuilder.AppendLine(
                """
                // <auto-generated />
                using JavaNETInterface.Jni;
                using JavaNETInterface.Wrappers;
                """);
            klassBuilder.AppendLine();
            if (!string.IsNullOrWhiteSpace(klass.Package))
            {
                klassBuilder.AppendLine($"namespace {klass.Package};");
                klassBuilder.AppendLine();
            }
            klassBuilder.AppendLine($"public unsafe class {cleanedName} : JniObject");
            klassBuilder.AppendLine("{");

            // Service members
            klassBuilder.AppendLine(
                """
                    public static JClass* Class { get; private set; }
                    private static readonly Lock lockObject = new();
                    private static bool initialized;
                """);

            klassBuilder.AppendLine();

            // Field definitions
            klassBuilder.AppendLine(string.Join("\n", klass.Fields.Select(f => "    " + GetFieldDefinition(f!.Name.Replace("$", "_")))));

            klassBuilder.AppendLine();

            //Method definitions
            klassBuilder.AppendLine(string.Join("\n", methodDatas.Select(md => "    " + GetMethodDefinition(md.Alias))));

            klassBuilder.AppendLine();

            // Constructor
            klassBuilder.AppendLine($"    public {cleanedName}(JniEnv* env, JObject* obj) : base(env, obj)");
            klassBuilder.AppendLine($"        => Initialize(env);");

            klassBuilder.AppendLine();

            // Initialize method
            klassBuilder.AppendLine(
                """
                    public static void Initialize(JniEnv* env)
                    {
                        lock(lockObject)
                        {
                            if(initialized)
                                return;

                """);

            string classPath = string.IsNullOrWhiteSpace(klass.Package) ? klass.Name : $"{klass.Package.Replace(".", "/")}/{klass.Name}";

            klassBuilder.AppendLine($"            Class = env->FindClass(\"{classPath}\");");
            klassBuilder.AppendLine();
            klassBuilder.AppendLine(string.Join("\n", klass.Fields.Select(f => "            " + GetFieldInitialization(f!))));
            klassBuilder.AppendLine();
            klassBuilder.AppendLine(string.Join("\n", methodDatas.Select(md => "            " + GetMethodInitialization($"{md.Alias.Replace("$", "_")}_MethodId", md.Method))));
            klassBuilder.AppendLine();
            klassBuilder.AppendLine($"            initialized = true;");
            klassBuilder.AppendLine("        }");
            klassBuilder.AppendLine("    }");

            //Accessors
            if (generateAccessors)
                AppendAccessors(klass, klassBuilder);

            // Methods
            var constructors = methodDatas.Where(md => md.Method.IsConstructor);
            klassBuilder.AppendLine(string.Join("\n", constructors.Select(md => GetSharpConstructorDefinition(klass, md))));
            klassBuilder.AppendLine(string.Join("\n", methodDatas.Except(constructors).Select(GetSharpMethodDefinition)));

            klassBuilder.Append('}');

            return klassBuilder.ToString();
        }

        private static string GetSharpMethodDefinition(MethodData methodData)
            => GetSharpMethodDefinition(methodData.Method, methodData.Alias);

        private static string GetSharpMethodDefinition(JavaMethod jMethod, string? alias = null)
        {
            StringBuilder sb = new();
            string type = ConvertType(jMethod.ReturnType);
            string cleanedName = cleanedName = jMethod.Name.Replace("$", "_");
            string cleanedAlias = alias?.Replace("$", "_") ?? cleanedName;
            string name = FirstCharToUpper(cleanedName) + (jMethod.IsConstructor ? "_Constructor" : string.Empty);

            string env = jMethod.IsStatic ? "env" : "_env";
            string[] argTypes = [.. jMethod.Arguments.Select(ConvertType)];

            (string jvalueDefinition, List<string> refsToDelete) = GetJValueArgsDefinition("args", env, argTypes);

            sb.AppendLine(
                $"""
                        /// <summary>
                        /// To be documented
                        /// </summary>{string.Join("", jMethod.Arguments.Select((a,i) => (a,i)).Where(pair => !IsPrimitive(pair.a)).Select(pair => $"\n    /// <param name=\"arg{pair.i}\">{pair.a}</param>"))}
                        /// <returns>{jMethod.ReturnType}</returns>
                    """);

            sb.AppendLine($"    public {(jMethod.IsStatic ? "static " : "")}{type} {name}({GetArgsDefinition(jMethod.Arguments, jMethod.IsStatic)})");
            sb.AppendLine("    {");

            if (!string.IsNullOrWhiteSpace(jvalueDefinition))
                sb.AppendLine("        " + jvalueDefinition);

            sb.AppendLine($"        {(type == "void" ? "" : "var result = ")}{env}->{GetCallSig(jMethod.ReturnType, jMethod.Arguments.Length, jMethod.IsStatic)}{GetCallArgs(cleanedAlias, jMethod.Arguments.Length, jMethod.IsStatic)};");

            if (refsToDelete.Count > 0)
                sb.AppendLine($"{string.Join(" ", refsToDelete.Select(r => $"        {env}->DeleteLocalRef({r});\n"))}");

            if (type == "string")
            {
                sb.AppendLine($"        string stringResult = {env}->JStringToString((JString*)result);");
                sb.AppendLine($"        {env}->DeleteLocalRef(result);");
                sb.AppendLine("        return stringResult;");
            }
            else if (type != "void" && type != "JObject*")
                sb.AppendLine($"        return ({type})result;");
            else if(type != "void")
                sb.AppendLine("        return result;");

            sb.Append("    }");

            return sb.ToString();
        }

        private static string GetMethodDefinition(string name)
            => $"private static JMethodID* {name.Replace("$", "_")}_MethodId;";
        private static string GetMethodInitialization(string fieldName, JavaMethod method)
            => $"{fieldName} = env->Get{(method.IsStatic ? "Static" : string.Empty)}MethodID(Class, \"{(method.IsConstructor ? "<init>" : method.Name.Replace("$", "_"))}\", \"({string.Join(string.Empty, method.Arguments.Select(ConvertToDescriptor))}){ConvertToDescriptor(method.ReturnType)}\");";

        private static string GetFieldDefinition(string name)
            => $"private static JFieldID* {name}_FieldId;";
        private static string GetFieldInitialization(JavaField field)
            => $"{field.Name.Replace("$", "_")}_FieldId = env->Get{(field.IsStatic ? "Static" : string.Empty)}FieldID(Class, \"{field.Name}\", \"{ConvertToDescriptor(field.Type)}\");";

        /// <summary>
        /// Generates field accessors, excluding fields where the accessor already exists in the class.
        /// </summary>
        private static void AppendAccessors(JavaClass klass, StringBuilder klassBuilder)
        {
            var existingMethods = klass.Methods.Select(m => FirstCharToUpper(m!.Name)).ToHashSet();

            klassBuilder.AppendLine(string.Join("\n", klass.Fields.Where(f => !existingMethods.Contains($"Get{FirstCharToUpper(f!.Name)}")).Select(f => GetSharpAccessorDefinition(f!, AccessorType.Getter))));
            klassBuilder.AppendLine();
            klassBuilder.AppendLine(string.Join("\n", klass.Fields.Where(f => !existingMethods.Contains($"Set{FirstCharToUpper(f!.Name)}")).Select(f => GetSharpAccessorDefinition(f!, AccessorType.Setter))));
            klassBuilder.AppendLine();
        }

        private static string GetSharpAccessorDefinition(JavaField jField, AccessorType accessorType)
        {
            StringBuilder sb = new();
            string paramDoc = accessorType == AccessorType.Setter ? $"\n    /// <param name=\"value\">{jField.Type}</param>" : string.Empty;
            string type = ConvertType(jField.Type);
            string env = jField.IsStatic ? "env" : "_env";
            string cleanedFieldName = jField.Name.Replace("$", "_");
            string prefix = accessorType == AccessorType.Getter ? "Get" : "Set";

            if (type == "JObject*")
                sb.AppendLine(
                    $"""
                        /// <summary>
                        /// To be documented
                        /// </summary>{paramDoc}
                        {(accessorType == AccessorType.Getter ? $"/// <returns>{jField.Type}</returns>" : string.Empty)}
                    """);
            sb.AppendLine($"    public {(jField.IsStatic ? "static " : "")}{(accessorType == AccessorType.Getter ? type : "void")} {prefix}{FirstCharToUpper(cleanedFieldName)}({GetAccessorArgs(jField, accessorType)})");
            sb.AppendLine("    {");

            string? refToDelete = null;

            if (accessorType == AccessorType.Setter)
            {
                if (type == "string")
                {
                    sb.AppendLine($"        JObject* stringValue = (JObject*){env}->NewStringUTF(value);");
                    sb.AppendLine("        " + GetFieldSetCall(jField, cleanedFieldName, "stringValue"));
                    refToDelete = "stringValue";
                }
                else
                    sb.AppendLine("        " + GetFieldSetCall(jField, cleanedFieldName, "value"));
            }
            else
                sb.AppendLine($"        var result = {GetFieldGetCall(jField, cleanedFieldName)}");

            if (refToDelete != null)
                sb.AppendLine("        " + $"{env}->DeleteLocalRef({refToDelete});");

            if (accessorType == AccessorType.Getter && type == "string")
            {
                sb.AppendLine($"        string stringResult = {env}->JStringToString((JString*)result);");
                sb.AppendLine($"        {env}->DeleteLocalRef(result);");
                sb.AppendLine("        return stringResult;");
            }
            else if (accessorType == AccessorType.Getter)
                sb.AppendLine($"        return result;");

            sb.Append("    }");

            return sb.ToString();
        }

        private static string GetCallSig(string returnType, int argsCount, bool isStatic)
        {
            string type = returnType == "void" || IsPrimitive(returnType) ? returnType : "Object";
            return $"Call{(isStatic ? "Static" : "")}{FirstCharToUpper(type)}Method{(argsCount > 0 ? "A" : "")}";
        }

        private static string GetCallArgs(string methodName, int argsCount, bool isStatic)
            => $"({(isStatic ? "Class" : "Object")}, {$"{methodName}_MethodId"}{(argsCount > 0 ? ", args" : "")})";

        private static string GetArgsDefinition(string[] argTypes, bool hasEnvArg)
        {
            string[] envArg = hasEnvArg ? ["JniEnv* env"] : [];
            return string.Join(", ", [..envArg, ..argTypes.Select((t, i) => $"{ConvertType(t)} arg{i}")]);
        }

        private static string GetAccessorArgs(JavaField field, AccessorType accessorType)
        {
            string envArg = field.IsStatic ? "JniEnv* env" : string.Empty;
            string valueArg = accessorType == AccessorType.Getter ? string.Empty : $"{ConvertType(field.Type)} value";
            string[] args = [envArg, valueArg];

            return string.Join(", ", args.Where(a => !string.IsNullOrWhiteSpace(a)));
        }

        private static string GetSharpConstructorDefinition(JavaClass jKlass, MethodData methodData)
        {
            if (!methodData.Method.IsConstructor)
                return string.Empty;

            StringBuilder sb = new();
            string cleanedAlias = methodData.Alias.Replace("$", "_");
            string cleanedType = jKlass.Name.Replace("$", "_");
            string[] arguments = methodData.Method.Arguments;


            string env = "env";
            string[] argTypes = [.. arguments.Select(ConvertType)];

            (string jvalueDefinition, List<string> refsToDelete) = GetJValueArgsDefinition("args", env, argTypes);

            sb.AppendLine(
                $"""
                        /// <summary>
                        /// To be documented
                        /// </summary>{string.Join("", methodData.Method.Arguments.Select((a, i) => (a, i)).Where(pair => !IsPrimitive(pair.a)).Select(pair => $"\n    /// <param name=\"arg{pair.i}\">{pair.a}</param>"))}
                    """);

            sb.AppendLine($"    public static {cleanedType} {cleanedAlias}_Constructor({GetArgsDefinition(arguments, true)})");
            sb.AppendLine("    {");
            sb.AppendLine($"        Initialize({env});");

            if (!string.IsNullOrWhiteSpace(jvalueDefinition))
                sb.AppendLine("        " + jvalueDefinition);

            sb.AppendLine($"        var result = {GetNewCall($"{cleanedAlias}_MethodId", arguments.Length)}");

            if (refsToDelete.Count > 0)
                sb.AppendLine($"{string.Join(" ", refsToDelete.Select(r => $"        {env}->DeleteLocalRef({r});\n"))}");

            sb.AppendLine($"        return new({env}, result);");

            sb.Append("    }");

            return sb.ToString();
        }

        private static string GetNewCall(string methodFieldName, int argsCount)
            => $"env->NewObject{(argsCount > 0 ? "A" : string.Empty)}(Class, {methodFieldName}{(argsCount > 0 ? ", args" : string.Empty)});";

        private static (string definition, List<string> refsToDelete) GetJValueArgsDefinition(string variableName, string env, string[] argTypes, string[]? argNames = null)
        {
            if (argTypes.Length == 0)
                return (string.Empty, []);

            StringBuilder sb = new();
            sb.AppendLine($"JValue* {variableName} = stackalloc JValue[{argTypes.Length}];");

            string[] names = argNames is null ? [.. argTypes.Select((_, i) => $"arg{i}")] : argNames;

            List<string> deleteLocalRef = [];

            for (int i = 0; i < argTypes.Length; i++)
            {
                string jvalueField = GetJValueField(argTypes[i]);

                switch (argTypes[i])
                {
                    case "string":
                        sb.AppendLine($"        JObject* stringArg{i} = (JObject*){env}->NewStringUTF({names[i]});");
                        sb.AppendLine($"        {variableName}[{i}].{jvalueField} = stringArg{i};");
                        deleteLocalRef.Add($"stringArg{i}");
                        break;
                    case "bool":
                        sb.AppendLine($"        {variableName}[{i}].{jvalueField} = (byte)({names[i]} ? 1 : 0);");
                        break;
                    default:
                        sb.AppendLine($"        {variableName}[{i}].{jvalueField} = {(argTypes[i].Contains("Array*") ? "(JObject*)" : string.Empty)}{names[i]};");
                        break;
                }
            }

            return (sb.ToString(), deleteLocalRef);
        }

        private static string GetFieldGetCall(JavaField field, string fieldName)
        {
            string env = field.IsStatic ? "env" : "_env";
            string prefix = field.IsStatic ? "Static" : string.Empty;
            string type = IsPrimitive(field.Type) ? FirstCharToUpper(field.Type) : "Object";
            string source = field.IsStatic ? "Class" : "Object";

            return $"{env}->Get{prefix}{type}Field({source}, {fieldName}_FieldId);";
        }

        private static string GetFieldSetCall(JavaField field, string fieldName, string argName)
        {
            string env = field.IsStatic ? "env" : "_env";
            string @static = field.IsStatic ? "Static" : string.Empty;
            string type = IsPrimitive(field.Type) ? FirstCharToUpper(field.Type) : "Object";
            string source = field.IsStatic ? "Class" : "Object";
            string argPrefix = type == "JArray*" ? "(JObject*)" : string.Empty;

            return $"{env}->Set{@static}{type}Field({source}, {fieldName}_FieldId, {argPrefix}{argName});";
        }

        private static List<MethodData> GroupMethodOverloads(IEnumerable<JavaMethod> methods)
        {
            IEnumerable<MethodData> overloads = methods.GroupBy(m => m.Name).SelectMany(g =>
            {
                if (g.Count() == 1)
                    return [new MethodData(g.First().Name, g.First())];

                return g.Select((m, i)=> new MethodData($"{m.Name}{i}", m));
            });

            return [..overloads];
        }

        private static string FirstCharToUpper(string text)
            => char.ToUpper(text[0]) + text[1..];
    }
}
