// <auto-generated />
using java.io;
using JavaNETInterface.Jni;
using JavaNETInterface.Wrappers;

namespace java.lang;

public unsafe class System : JniObject
{
    public static JClass* Class { get; private set; }
    private static readonly Lock lockObject = new();
    private static bool initialized;

    private static JFieldID* in_FieldId;
    private static JFieldID* out_FieldId;
    private static JFieldID* err_FieldId;
    private static JFieldID* initialIn_FieldId;
    private static JFieldID* initialErr_FieldId;
    private static JFieldID* notSupportedJnuEncoding_FieldId;
    private static JFieldID* cons_FieldId;
    private static JFieldID* props_FieldId;
    private static JFieldID* lineSeparator_FieldId;
    private static JFieldID* bootLayer_FieldId;

    private static JMethodID* registerNatives_MethodId;
    private static JMethodID* System_MethodId;
    private static JMethodID* setIn_MethodId;
    private static JMethodID* setOut_MethodId;
    private static JMethodID* setErr_MethodId;
    private static JMethodID* console_MethodId;
    private static JMethodID* inheritedChannel_MethodId;
    private static JMethodID* setIn0_MethodId;
    private static JMethodID* setOut0_MethodId;
    private static JMethodID* setErr0_MethodId;
    private static JMethodID* setSecurityManager_MethodId;
    private static JMethodID* getSecurityManager_MethodId;
    private static JMethodID* currentTimeMillis_MethodId;
    private static JMethodID* nanoTime_MethodId;
    private static JMethodID* arraycopy_MethodId;
    private static JMethodID* identityHashCode_MethodId;
    private static JMethodID* getProperties_MethodId;
    private static JMethodID* lineSeparator_MethodId;
    private static JMethodID* setProperties_MethodId;
    private static JMethodID* getProperty0_MethodId;
    private static JMethodID* getProperty1_MethodId;
    private static JMethodID* setProperty_MethodId;
    private static JMethodID* clearProperty_MethodId;
    private static JMethodID* checkKey_MethodId;
    private static JMethodID* getenv0_MethodId;
    private static JMethodID* getenv1_MethodId;
    private static JMethodID* getLogger0_MethodId;
    private static JMethodID* getLogger1_MethodId;
    private static JMethodID* exit_MethodId;
    private static JMethodID* gc_MethodId;
    private static JMethodID* runFinalization_MethodId;
    private static JMethodID* load_MethodId;
    private static JMethodID* loadLibrary_MethodId;
    private static JMethodID* mapLibraryName_MethodId;
    private static JMethodID* newPrintStream_MethodId;
    private static JMethodID* logInitException_MethodId;
    //private static JMethodID* createProperties_MethodId; java.lang.NoSuchMethodError
    private static JMethodID* initPhase1_MethodId;
    private static JMethodID* initPhase2_MethodId;
    private static JMethodID* initPhase3_MethodId;
    private static JMethodID* setJavaLangAccess_MethodId;

    public System(JniEnv* env, JObject* obj) : base(env, obj)
        => Initialize(env);

    public static void Initialize(JniEnv* env)
    {
        lock(lockObject)
        {
            if(initialized)
                return;

            Class = env->FindClass("java/lang/System");

            in_FieldId = env->GetStaticFieldID(Class, "in", "Ljava/io/InputStream;");
            out_FieldId = env->GetStaticFieldID(Class, "out", "Ljava/io/PrintStream;");
            err_FieldId = env->GetStaticFieldID(Class, "err", "Ljava/io/PrintStream;");
            initialIn_FieldId = env->GetStaticFieldID(Class, "initialIn", "Ljava/io/InputStream;");
            initialErr_FieldId = env->GetStaticFieldID(Class, "initialErr", "Ljava/io/PrintStream;");
            notSupportedJnuEncoding_FieldId = env->GetStaticFieldID(Class, "notSupportedJnuEncoding", "Ljava/lang/String;");
            cons_FieldId = env->GetStaticFieldID(Class, "cons", "Ljava/io/Console;");
            props_FieldId = env->GetStaticFieldID(Class, "props", "Ljava/util/Properties;");
            lineSeparator_FieldId = env->GetStaticFieldID(Class, "lineSeparator", "Ljava/lang/String;");
            bootLayer_FieldId = env->GetStaticFieldID(Class, "bootLayer", "Ljava/lang/ModuleLayer;");

            registerNatives_MethodId = env->GetStaticMethodID(Class, "registerNatives", "()V");
            System_MethodId = env->GetMethodID(Class, "<init>", "()V");
            setIn_MethodId = env->GetStaticMethodID(Class, "setIn", "(Ljava/io/InputStream;)V");
            setOut_MethodId = env->GetStaticMethodID(Class, "setOut", "(Ljava/io/PrintStream;)V");
            setErr_MethodId = env->GetStaticMethodID(Class, "setErr", "(Ljava/io/PrintStream;)V");
            console_MethodId = env->GetStaticMethodID(Class, "console", "()Ljava/io/Console;");
            inheritedChannel_MethodId = env->GetStaticMethodID(Class, "inheritedChannel", "()Ljava/nio/channels/Channel;");
            setIn0_MethodId = env->GetStaticMethodID(Class, "setIn0", "(Ljava/io/InputStream;)V");
            setOut0_MethodId = env->GetStaticMethodID(Class, "setOut0", "(Ljava/io/PrintStream;)V");
            setErr0_MethodId = env->GetStaticMethodID(Class, "setErr0", "(Ljava/io/PrintStream;)V");
            setSecurityManager_MethodId = env->GetStaticMethodID(Class, "setSecurityManager", "(Ljava/lang/SecurityManager;)V");
            getSecurityManager_MethodId = env->GetStaticMethodID(Class, "getSecurityManager", "()Ljava/lang/SecurityManager;");
            currentTimeMillis_MethodId = env->GetStaticMethodID(Class, "currentTimeMillis", "()J");
            nanoTime_MethodId = env->GetStaticMethodID(Class, "nanoTime", "()J");
            arraycopy_MethodId = env->GetStaticMethodID(Class, "arraycopy", "(Ljava/lang/Object;ILjava/lang/Object;II)V");
            identityHashCode_MethodId = env->GetStaticMethodID(Class, "identityHashCode", "(Ljava/lang/Object;)I");
            getProperties_MethodId = env->GetStaticMethodID(Class, "getProperties", "()Ljava/util/Properties;");
            lineSeparator_MethodId = env->GetStaticMethodID(Class, "lineSeparator", "()Ljava/lang/String;");
            setProperties_MethodId = env->GetStaticMethodID(Class, "setProperties", "(Ljava/util/Properties;)V");
            getProperty0_MethodId = env->GetStaticMethodID(Class, "getProperty", "(Ljava/lang/String;)Ljava/lang/String;");
            getProperty1_MethodId = env->GetStaticMethodID(Class, "getProperty", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
            setProperty_MethodId = env->GetStaticMethodID(Class, "setProperty", "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;");
            clearProperty_MethodId = env->GetStaticMethodID(Class, "clearProperty", "(Ljava/lang/String;)Ljava/lang/String;");
            checkKey_MethodId = env->GetStaticMethodID(Class, "checkKey", "(Ljava/lang/String;)V");
            getenv0_MethodId = env->GetStaticMethodID(Class, "getenv", "(Ljava/lang/String;)Ljava/lang/String;");
            getenv1_MethodId = env->GetStaticMethodID(Class, "getenv", "()Ljava/util/Map;");
            getLogger0_MethodId = env->GetStaticMethodID(Class, "getLogger", "(Ljava/lang/String;)Ljava/lang/System$Logger;");
            getLogger1_MethodId = env->GetStaticMethodID(Class, "getLogger", "(Ljava/lang/String;Ljava/util/ResourceBundle;)Ljava/lang/System$Logger;");
            exit_MethodId = env->GetStaticMethodID(Class, "exit", "(I)V");
            gc_MethodId = env->GetStaticMethodID(Class, "gc", "()V");
            runFinalization_MethodId = env->GetStaticMethodID(Class, "runFinalization", "()V");
            load_MethodId = env->GetStaticMethodID(Class, "load", "(Ljava/lang/String;)V");
            loadLibrary_MethodId = env->GetStaticMethodID(Class, "loadLibrary", "(Ljava/lang/String;)V");
            mapLibraryName_MethodId = env->GetStaticMethodID(Class, "mapLibraryName", "(Ljava/lang/String;)Ljava/lang/String;");
            newPrintStream_MethodId = env->GetStaticMethodID(Class, "newPrintStream", "(Ljava/io/OutputStream;Ljava/lang/String;)Ljava/io/PrintStream;");
            logInitException_MethodId = env->GetStaticMethodID(Class, "logInitException", "(ZZLjava/lang/String;Ljava/lang/Throwable;)V");
            //createProperties_MethodId = env->GetStaticMethodID(Class, "createProperties", "(Ljava/util/Map;Ljava/lang/String;)Ljava/util/Properties;"); java.lang.NoSuchMethodError
            initPhase1_MethodId = env->GetStaticMethodID(Class, "initPhase1", "()V");
            initPhase2_MethodId = env->GetStaticMethodID(Class, "initPhase2", "(ZZ)I");
            initPhase3_MethodId = env->GetStaticMethodID(Class, "initPhase3", "()V");
            setJavaLangAccess_MethodId = env->GetStaticMethodID(Class, "setJavaLangAccess", "()V");

            initialized = true;
        }
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.InputStream</returns>
    public static InputStream GetIn(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, in_FieldId);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.PrintStream</returns>
    public static PrintStream GetOut(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, out_FieldId);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.PrintStream</returns>
    public static PrintStream GetErr(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, err_FieldId);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.InputStream</returns>
    public static InputStream GetInitialIn(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, initialIn_FieldId);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.PrintStream</returns>
    public static PrintStream GetInitialErr(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, initialErr_FieldId);
        return new(env, result);
    }
    public static string GetNotSupportedJnuEncoding(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, notSupportedJnuEncoding_FieldId);
        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.Console</returns>
    public static JObject* GetCons(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, cons_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Properties</returns>
    public static JObject* GetProps(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, props_FieldId);
        return result;
    }
    public static string GetLineSeparator(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, lineSeparator_FieldId);
        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.ModuleLayer</returns>
    public static JObject* GetBootLayer(JniEnv* env)
    {
        var result = env->GetStaticObjectField(Class, bootLayer_FieldId);
        return result;
    }

    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.io.InputStream</param>
    
    public static void SetInitialIn(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, initialIn_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.io.PrintStream</param>
    
    public static void SetInitialErr(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, initialErr_FieldId, value);
    }
    public static void SetNotSupportedJnuEncoding(JniEnv* env, string value)
    {
        JObject* stringValue = (JObject*)env->NewStringUTF(value);
        env->SetStaticObjectField(Class, notSupportedJnuEncoding_FieldId, stringValue);
        env->DeleteLocalRef(stringValue);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.io.Console</param>
    
    public static void SetCons(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, cons_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.Properties</param>
    
    public static void SetProps(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, props_FieldId, value);
    }
    public static void SetLineSeparator(JniEnv* env, string value)
    {
        JObject* stringValue = (JObject*)env->NewStringUTF(value);
        env->SetStaticObjectField(Class, lineSeparator_FieldId, stringValue);
        env->DeleteLocalRef(stringValue);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.lang.ModuleLayer</param>
    
    public static void SetBootLayer(JniEnv* env, JObject* value)
    {
        env->SetStaticObjectField(Class, bootLayer_FieldId, value);
    }

    /// <summary>
    /// To be documented
    /// </summary>
    public static System System_Constructor(JniEnv* env)
    {
        Initialize(env);
        var result = env->NewObject(Class, System_MethodId);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public static void RegisterNatives(JniEnv* env)
    {
        env->CallStaticVoidMethod(Class, registerNatives_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.InputStream</param>
    /// <returns>void</returns>
    public static void SetIn(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        env->CallStaticVoidMethodA(Class, setIn_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.PrintStream</param>
    /// <returns>void</returns>
    public static void SetOut(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        env->CallStaticVoidMethodA(Class, setOut_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.PrintStream</param>
    /// <returns>void</returns>
    public static void SetErr(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        env->CallStaticVoidMethodA(Class, setErr_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.Console</returns>
    public static JObject* Console(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, console_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.nio.channels.Channel</returns>
    public static JObject* InheritedChannel(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, inheritedChannel_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.InputStream</param>
    /// <returns>void</returns>
    public static void SetIn0(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        env->CallStaticVoidMethodA(Class, setIn0_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.PrintStream</param>
    /// <returns>void</returns>
    public static void SetOut0(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        env->CallStaticVoidMethodA(Class, setOut0_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.PrintStream</param>
    /// <returns>void</returns>
    public static void SetErr0(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        env->CallStaticVoidMethodA(Class, setErr0_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.SecurityManager</param>
    /// <returns>void</returns>
    public static void SetSecurityManager(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        env->CallStaticVoidMethodA(Class, setSecurityManager_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.SecurityManager</returns>
    public static JObject* GetSecurityManager(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, getSecurityManager_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>long</returns>
    public static long CurrentTimeMillis(JniEnv* env)
    {
        var result = env->CallStaticLongMethod(Class, currentTimeMillis_MethodId);
        return (long)result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>long</returns>
    public static long NanoTime(JniEnv* env)
    {
        var result = env->CallStaticLongMethod(Class, nanoTime_MethodId);
        return (long)result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.Object</param>
    /// <param name="arg2">java.lang.Object</param>
    /// <returns>void</returns>
    public static void Arraycopy(JniEnv* env, JObject* arg0, int arg1, JObject* arg2, int arg3, int arg4)
    {
        JValue* args = stackalloc JValue[5];
        args[0].L = arg0;
        args[1].I = arg1;
        args[2].L = arg2;
        args[3].I = arg3;
        args[4].I = arg4;

        env->CallStaticVoidMethodA(Class, arraycopy_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.Object</param>
    /// <returns>int</returns>
    public static int IdentityHashCode(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = env->CallStaticIntMethodA(Class, identityHashCode_MethodId, args);
        return (int)result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Properties</returns>
    public static JObject* GetProperties(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, getProperties_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.String</returns>
    public static string LineSeparator(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, lineSeparator_MethodId);
        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.Properties</param>
    /// <returns>void</returns>
    public static void SetProperties(JniEnv* env, JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        env->CallStaticVoidMethodA(Class, setProperties_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public static string GetProperty(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->CallStaticObjectMethodA(Class, getProperty0_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <param name="arg1">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public static string GetProperty(JniEnv* env, string arg0, string arg1)
    {
        JValue* args = stackalloc JValue[2];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->CallStaticObjectMethodA(Class, getProperty1_MethodId, args);
        env->DeleteLocalRef(stringArg0);
         env->DeleteLocalRef(stringArg1);

        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <param name="arg1">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public static string SetProperty(JniEnv* env, string arg0, string arg1)
    {
        JValue* args = stackalloc JValue[2];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->CallStaticObjectMethodA(Class, setProperty_MethodId, args);
        env->DeleteLocalRef(stringArg0);
         env->DeleteLocalRef(stringArg1);

        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public static string ClearProperty(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->CallStaticObjectMethodA(Class, clearProperty_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>void</returns>
    public static void CheckKey(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        env->CallStaticVoidMethodA(Class, checkKey_MethodId, args);
        env->DeleteLocalRef(stringArg0);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public static string Getenv(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->CallStaticObjectMethodA(Class, getenv0_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Map<java.lang.String, java.lang.String></returns>
    public static JObject* Getenv(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, getenv1_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.System$Logger</returns>
    public static JObject* GetLogger(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->CallStaticObjectMethodA(Class, getLogger0_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <param name="arg1">java.util.ResourceBundle</param>
    /// <returns>java.lang.System$Logger</returns>
    public static JObject* GetLogger(JniEnv* env, string arg0, JObject* arg1)
    {
        JValue* args = stackalloc JValue[2];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;
        args[1].L = arg1;

        var result = env->CallStaticObjectMethodA(Class, getLogger1_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public static void Exit(JniEnv* env, int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        env->CallStaticVoidMethodA(Class, exit_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public static void Gc(JniEnv* env)
    {
        env->CallStaticVoidMethod(Class, gc_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public static void RunFinalization(JniEnv* env)
    {
        env->CallStaticVoidMethod(Class, runFinalization_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>void</returns>
    public static void Load(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        env->CallStaticVoidMethodA(Class, load_MethodId, args);
        env->DeleteLocalRef(stringArg0);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>void</returns>
    public static void LoadLibrary(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        env->CallStaticVoidMethodA(Class, loadLibrary_MethodId, args);
        env->DeleteLocalRef(stringArg0);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.lang.String</returns>
    public static string MapLibraryName(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->CallStaticObjectMethodA(Class, mapLibraryName_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        string stringResult = env->JStringToString((JString*)result);
        env->DeleteLocalRef(result);
        return stringResult;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.OutputStream</param>
    /// <param name="arg1">java.lang.String</param>
    /// <returns>java.io.PrintStream</returns>
    public static JObject* NewPrintStream(JniEnv* env, JObject* arg0, string arg1)
    {
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->CallStaticObjectMethodA(Class, newPrintStream_MethodId, args);
        env->DeleteLocalRef(stringArg1);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg2">java.lang.String</param>
    /// <param name="arg3">java.lang.Throwable</param>
    /// <returns>void</returns>
    public static void LogInitException(JniEnv* env, bool arg0, bool arg1, string arg2, JObject* arg3)
    {
        JValue* args = stackalloc JValue[4];
        args[0].Z = (byte)(arg0 ? 1 : 0);
        args[1].Z = (byte)(arg1 ? 1 : 0);
        JObject* stringArg2 = (JObject*)env->NewStringUTF(arg2);
        args[2].L = stringArg2;
        args[3].L = arg3;

        env->CallStaticVoidMethodA(Class, logInitException_MethodId, args);
        env->DeleteLocalRef(stringArg2);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.Map<java.lang.String</param>
    /// <param name="arg1">java.lang.String></param>
    /// <returns>java.util.Properties</returns>
    //public static JObject* CreateProperties(JniEnv* env, JObject* arg0, JObject* arg1) java.lang.NoSuchMethodError
    //{
    //    JValue* args = stackalloc JValue[2];
    //    args[0].L = arg0;
    //    args[1].L = arg1;

    //    var result = env->CallStaticObjectMethodA(Class, createProperties_MethodId, args);
    //    return result;
    //}
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public static void InitPhase1(JniEnv* env)
    {
        env->CallStaticVoidMethod(Class, initPhase1_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>int</returns>
    public static int InitPhase2(JniEnv* env, bool arg0, bool arg1)
    {
        JValue* args = stackalloc JValue[2];
        args[0].Z = (byte)(arg0 ? 1 : 0);
        args[1].Z = (byte)(arg1 ? 1 : 0);

        var result = env->CallStaticIntMethodA(Class, initPhase2_MethodId, args);
        return (int)result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public static void InitPhase3(JniEnv* env)
    {
        env->CallStaticVoidMethod(Class, initPhase3_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public static void SetJavaLangAccess(JniEnv* env)
    {
        env->CallStaticVoidMethod(Class, setJavaLangAccess_MethodId);
    }
}