// <auto-generated />
using JavaNETInterface.Jni;
using JavaNETInterface.Wrappers;

namespace java.io;

public unsafe class InputStream : JniObject
{
    public static JClass* Class { get; private set; }
    private static readonly Lock lockObject = new();
    private static bool initialized;

    private static JFieldID* MAX_SKIP_BUFFER_SIZE_FieldId;
    private static JFieldID* DEFAULT_BUFFER_SIZE_FieldId;
    private static JFieldID* MAX_BUFFER_SIZE_FieldId;

    private static JMethodID* InputStream_MethodId;
    private static JMethodID* nullInputStream_MethodId;
    private static JMethodID* read0_MethodId;
    private static JMethodID* read1_MethodId;
    private static JMethodID* read2_MethodId;
    private static JMethodID* readAllBytes_MethodId;
    private static JMethodID* readNBytes0_MethodId;
    private static JMethodID* readNBytes1_MethodId;
    private static JMethodID* skip_MethodId;
    private static JMethodID* skipNBytes_MethodId;
    private static JMethodID* available_MethodId;
    private static JMethodID* close_MethodId;
    private static JMethodID* mark_MethodId;
    private static JMethodID* reset_MethodId;
    private static JMethodID* markSupported_MethodId;
    private static JMethodID* transferTo_MethodId;

    public InputStream(JniEnv* env, JObject* obj) : base(env, obj)
        => Initialize(env);

    public static void Initialize(JniEnv* env)
    {
        lock(lockObject)
        {
            if(initialized)
                return;

            Class = env->FindClass("java/io/InputStream");

            MAX_SKIP_BUFFER_SIZE_FieldId = env->GetStaticFieldID(Class, "MAX_SKIP_BUFFER_SIZE", "I");
            DEFAULT_BUFFER_SIZE_FieldId = env->GetStaticFieldID(Class, "DEFAULT_BUFFER_SIZE", "I");
            MAX_BUFFER_SIZE_FieldId = env->GetStaticFieldID(Class, "MAX_BUFFER_SIZE", "I");

            InputStream_MethodId = env->GetMethodID(Class, "<init>", "()V");
            nullInputStream_MethodId = env->GetStaticMethodID(Class, "nullInputStream", "()Ljava/io/InputStream;");
            read0_MethodId = env->GetMethodID(Class, "read", "()I");
            read1_MethodId = env->GetMethodID(Class, "read", "([B)I");
            read2_MethodId = env->GetMethodID(Class, "read", "([BII)I");
            readAllBytes_MethodId = env->GetMethodID(Class, "readAllBytes", "()[B");
            readNBytes0_MethodId = env->GetMethodID(Class, "readNBytes", "(I)[B");
            readNBytes1_MethodId = env->GetMethodID(Class, "readNBytes", "([BII)I");
            skip_MethodId = env->GetMethodID(Class, "skip", "(J)J");
            skipNBytes_MethodId = env->GetMethodID(Class, "skipNBytes", "(J)V");
            available_MethodId = env->GetMethodID(Class, "available", "()I");
            close_MethodId = env->GetMethodID(Class, "close", "()V");
            mark_MethodId = env->GetMethodID(Class, "mark", "(I)V");
            reset_MethodId = env->GetMethodID(Class, "reset", "()V");
            markSupported_MethodId = env->GetMethodID(Class, "markSupported", "()Z");
            transferTo_MethodId = env->GetMethodID(Class, "transferTo", "(Ljava/io/OutputStream;)J");

            initialized = true;
        }
    }
    public static int GetMAX_SKIP_BUFFER_SIZE(JniEnv* env)
    {
        var result = env->GetStaticIntField(Class, MAX_SKIP_BUFFER_SIZE_FieldId);
        return result;
    }
    public static int GetDEFAULT_BUFFER_SIZE(JniEnv* env)
    {
        var result = env->GetStaticIntField(Class, DEFAULT_BUFFER_SIZE_FieldId);
        return result;
    }
    public static int GetMAX_BUFFER_SIZE(JniEnv* env)
    {
        var result = env->GetStaticIntField(Class, MAX_BUFFER_SIZE_FieldId);
        return result;
    }

    public static void SetMAX_SKIP_BUFFER_SIZE(JniEnv* env, int value)
    {
        env->SetStaticIntField(Class, MAX_SKIP_BUFFER_SIZE_FieldId, value);
    }
    public static void SetDEFAULT_BUFFER_SIZE(JniEnv* env, int value)
    {
        env->SetStaticIntField(Class, DEFAULT_BUFFER_SIZE_FieldId, value);
    }
    public static void SetMAX_BUFFER_SIZE(JniEnv* env, int value)
    {
        env->SetStaticIntField(Class, MAX_BUFFER_SIZE_FieldId, value);
    }

    /// <summary>
    /// To be documented
    /// </summary>
    public static InputStream InputStream_Constructor(JniEnv* env)
    {
        Initialize(env);
        var result = env->NewObject(Class, InputStream_MethodId);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.InputStream</returns>
    public static JObject* NullInputStream(JniEnv* env)
    {
        var result = env->CallStaticObjectMethod(Class, nullInputStream_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>int</returns>
    public int Read()
    {
        var result = _env->CallIntMethod(Object, read0_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">byte[]</param>
    /// <returns>int</returns>
    public int Read(JByteArray* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = (JObject*)arg0;

        var result = _env->CallIntMethodA(Object, read1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">byte[]</param>
    /// <returns>int</returns>
    public int Read(JByteArray* arg0, int arg1, int arg2)
    {
        JValue* args = stackalloc JValue[3];
        args[0].L = (JObject*)arg0;
        args[1].I = arg1;
        args[2].I = arg2;

        var result = _env->CallIntMethodA(Object, read2_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>byte[]</returns>
    public JByteArray* ReadAllBytes()
    {
        var result = _env->CallObjectMethod(Object, readAllBytes_MethodId);
        return (JByteArray*)result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>byte[]</returns>
    public JByteArray* ReadNBytes(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        var result = _env->CallObjectMethodA(Object, readNBytes0_MethodId, args);
        return (JByteArray*)result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">byte[]</param>
    /// <returns>int</returns>
    public int ReadNBytes(JByteArray* arg0, int arg1, int arg2)
    {
        JValue* args = stackalloc JValue[3];
        args[0].L = (JObject*)arg0;
        args[1].I = arg1;
        args[2].I = arg2;

        var result = _env->CallIntMethodA(Object, readNBytes1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>long</returns>
    public long Skip(long arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].J = arg0;

        var result = _env->CallLongMethodA(Object, skip_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void SkipNBytes(long arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].J = arg0;

        _env->CallVoidMethodA(Object, skipNBytes_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>int</returns>
    public int Available()
    {
        var result = _env->CallIntMethod(Object, available_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Close()
    {
        _env->CallVoidMethod(Object, close_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Mark(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        _env->CallVoidMethodA(Object, mark_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Reset()
    {
        _env->CallVoidMethod(Object, reset_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool MarkSupported()
    {
        var result = _env->CallBooleanMethod(Object, markSupported_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.OutputStream</param>
    /// <returns>long</returns>
    public long TransferTo(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallLongMethodA(Object, transferTo_MethodId, args);
        return result;
    }
}