// <auto-generated />
using JavaNETInterface.Jni;
using JavaNETInterface.Wrappers;

namespace java.io;

public unsafe class PrintStream : JniObject
{
    public static JClass* Class { get; private set; }
    private static readonly Lock lockObject = new();
    private static bool initialized;

    private static JFieldID* autoFlush_FieldId;
    private static JFieldID* trouble_FieldId;
    private static JFieldID* formatter_FieldId;
    private static JFieldID* charset_FieldId;
    private static JFieldID* textOut_FieldId;
    private static JFieldID* charOut_FieldId;
    private static JFieldID* closing_FieldId;

    private static JMethodID* toCharset_MethodId;
    private static JMethodID* PrintStream0_MethodId;
    private static JMethodID* PrintStream1_MethodId;
    private static JMethodID* PrintStream2_MethodId;
    private static JMethodID* PrintStream3_MethodId;
    private static JMethodID* PrintStream4_MethodId;
    private static JMethodID* PrintStream5_MethodId;
    private static JMethodID* PrintStream6_MethodId;
    private static JMethodID* PrintStream7_MethodId;
    private static JMethodID* PrintStream8_MethodId;
    private static JMethodID* PrintStream9_MethodId;
    private static JMethodID* PrintStream10_MethodId;
    private static JMethodID* PrintStream11_MethodId;
    private static JMethodID* ensureOpen_MethodId;
    private static JMethodID* flush_MethodId;
    private static JMethodID* close_MethodId;
    private static JMethodID* checkError_MethodId;
    private static JMethodID* setError_MethodId;
    private static JMethodID* clearError_MethodId;
    private static JMethodID* write0_MethodId;
    private static JMethodID* write1_MethodId;
    private static JMethodID* write2_MethodId;
    private static JMethodID* write3_MethodId;
    private static JMethodID* write4_MethodId;
    private static JMethodID* writeBytes_MethodId;
    private static JMethodID* writeln0_MethodId;
    private static JMethodID* writeln1_MethodId;
    private static JMethodID* newLine_MethodId;
    private static JMethodID* print0_MethodId;
    private static JMethodID* print1_MethodId;
    private static JMethodID* print2_MethodId;
    private static JMethodID* print3_MethodId;
    private static JMethodID* print4_MethodId;
    private static JMethodID* print5_MethodId;
    private static JMethodID* print6_MethodId;
    private static JMethodID* print7_MethodId;
    private static JMethodID* print8_MethodId;
    private static JMethodID* println0_MethodId;
    private static JMethodID* println1_MethodId;
    private static JMethodID* println2_MethodId;
    private static JMethodID* println3_MethodId;
    private static JMethodID* println4_MethodId;
    private static JMethodID* println5_MethodId;
    private static JMethodID* println6_MethodId;
    private static JMethodID* println7_MethodId;
    private static JMethodID* println8_MethodId;
    private static JMethodID* println9_MethodId;
    private static JMethodID* printf0_MethodId;
    private static JMethodID* printf1_MethodId;
    private static JMethodID* format0_MethodId;
    private static JMethodID* format1_MethodId;
    private static JMethodID* append0_MethodId;
    private static JMethodID* append1_MethodId;
    private static JMethodID* append2_MethodId;
    private static JMethodID* append3_MethodId;
    private static JMethodID* append4_MethodId;
    private static JMethodID* append5_MethodId;
    private static JMethodID* charset_MethodId;

    public PrintStream(JniEnv* env, JObject* obj) : base(env, obj)
        => Initialize(env);

    public static void Initialize(JniEnv* env)
    {
        lock(lockObject)
        {
            if(initialized)
                return;

            Class = env->FindClass("java/io/PrintStream");

            autoFlush_FieldId = env->GetFieldID(Class, "autoFlush", "Z");
            trouble_FieldId = env->GetFieldID(Class, "trouble", "Z");
            formatter_FieldId = env->GetFieldID(Class, "formatter", "Ljava/util/Formatter;");
            charset_FieldId = env->GetFieldID(Class, "charset", "Ljava/nio/charset/Charset;");
            textOut_FieldId = env->GetFieldID(Class, "textOut", "Ljava/io/BufferedWriter;");
            charOut_FieldId = env->GetFieldID(Class, "charOut", "Ljava/io/OutputStreamWriter;");
            closing_FieldId = env->GetFieldID(Class, "closing", "Z");

            toCharset_MethodId = env->GetStaticMethodID(Class, "toCharset", "(Ljava/lang/String;)Ljava/nio/charset/Charset;");
            PrintStream0_MethodId = env->GetMethodID(Class, "<init>", "(ZLjava/io/OutputStream;)V");
            PrintStream1_MethodId = env->GetMethodID(Class, "<init>", "(ZLjava/nio/charset/Charset;Ljava/io/OutputStream;)V");
            PrintStream2_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/OutputStream;)V");
            PrintStream3_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/OutputStream;Z)V");
            PrintStream4_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/OutputStream;ZLjava/lang/String;)V");
            PrintStream5_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/OutputStream;ZLjava/nio/charset/Charset;)V");
            PrintStream6_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/lang/String;)V");
            PrintStream7_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/lang/String;Ljava/lang/String;)V");
            PrintStream8_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/lang/String;Ljava/nio/charset/Charset;)V");
            PrintStream9_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/File;)V");
            PrintStream10_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/File;Ljava/lang/String;)V");
            PrintStream11_MethodId = env->GetMethodID(Class, "<init>", "(Ljava/io/File;Ljava/nio/charset/Charset;)V");
            ensureOpen_MethodId = env->GetMethodID(Class, "ensureOpen", "()V");
            flush_MethodId = env->GetMethodID(Class, "flush", "()V");
            close_MethodId = env->GetMethodID(Class, "close", "()V");
            checkError_MethodId = env->GetMethodID(Class, "checkError", "()Z");
            setError_MethodId = env->GetMethodID(Class, "setError", "()V");
            clearError_MethodId = env->GetMethodID(Class, "clearError", "()V");
            write0_MethodId = env->GetMethodID(Class, "write", "(I)V");
            write1_MethodId = env->GetMethodID(Class, "write", "([BII)V");
            write2_MethodId = env->GetMethodID(Class, "write", "([B)V");
            write3_MethodId = env->GetMethodID(Class, "write", "([C)V");
            write4_MethodId = env->GetMethodID(Class, "write", "(Ljava/lang/String;)V");
            writeBytes_MethodId = env->GetMethodID(Class, "writeBytes", "([B)V");
            writeln0_MethodId = env->GetMethodID(Class, "writeln", "([C)V");
            writeln1_MethodId = env->GetMethodID(Class, "writeln", "(Ljava/lang/String;)V");
            newLine_MethodId = env->GetMethodID(Class, "newLine", "()V");
            print0_MethodId = env->GetMethodID(Class, "print", "(Z)V");
            print1_MethodId = env->GetMethodID(Class, "print", "(C)V");
            print2_MethodId = env->GetMethodID(Class, "print", "(I)V");
            print3_MethodId = env->GetMethodID(Class, "print", "(J)V");
            print4_MethodId = env->GetMethodID(Class, "print", "(F)V");
            print5_MethodId = env->GetMethodID(Class, "print", "(D)V");
            print6_MethodId = env->GetMethodID(Class, "print", "([C)V");
            print7_MethodId = env->GetMethodID(Class, "print", "(Ljava/lang/String;)V");
            print8_MethodId = env->GetMethodID(Class, "print", "(Ljava/lang/Object;)V");
            println0_MethodId = env->GetMethodID(Class, "println", "()V");
            println1_MethodId = env->GetMethodID(Class, "println", "(Z)V");
            println2_MethodId = env->GetMethodID(Class, "println", "(C)V");
            println3_MethodId = env->GetMethodID(Class, "println", "(I)V");
            println4_MethodId = env->GetMethodID(Class, "println", "(J)V");
            println5_MethodId = env->GetMethodID(Class, "println", "(F)V");
            println6_MethodId = env->GetMethodID(Class, "println", "(D)V");
            println7_MethodId = env->GetMethodID(Class, "println", "([C)V");
            println8_MethodId = env->GetMethodID(Class, "println", "(Ljava/lang/String;)V");
            println9_MethodId = env->GetMethodID(Class, "println", "(Ljava/lang/Object;)V");
            printf0_MethodId = env->GetMethodID(Class, "printf", "(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;");
            printf1_MethodId = env->GetMethodID(Class, "printf", "(Ljava/util/Locale;Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;");
            format0_MethodId = env->GetMethodID(Class, "format", "(Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;");
            format1_MethodId = env->GetMethodID(Class, "format", "(Ljava/util/Locale;Ljava/lang/String;[Ljava/lang/Object;)Ljava/io/PrintStream;");
            append0_MethodId = env->GetMethodID(Class, "append", "(Ljava/lang/CharSequence;)Ljava/io/PrintStream;");
            append1_MethodId = env->GetMethodID(Class, "append", "(Ljava/lang/CharSequence;II)Ljava/io/PrintStream;");
            append2_MethodId = env->GetMethodID(Class, "append", "(C)Ljava/io/PrintStream;");
            append3_MethodId = env->GetMethodID(Class, "append", "(C)Ljava/lang/Appendable;");
            append4_MethodId = env->GetMethodID(Class, "append", "(Ljava/lang/CharSequence;II)Ljava/lang/Appendable;");
            append5_MethodId = env->GetMethodID(Class, "append", "(Ljava/lang/CharSequence;)Ljava/lang/Appendable;");
            charset_MethodId = env->GetMethodID(Class, "charset", "()Ljava/nio/charset/Charset;");

            initialized = true;
        }
    }
    public bool GetAutoFlush()
    {
        var result = _env->GetBooleanField(Object, autoFlush_FieldId);
        return result;
    }
    public bool GetTrouble()
    {
        var result = _env->GetBooleanField(Object, trouble_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.util.Formatter</returns>
    public JObject* GetFormatter()
    {
        var result = _env->GetObjectField(Object, formatter_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.nio.charset.Charset</returns>
    public JObject* GetCharset()
    {
        var result = _env->GetObjectField(Object, charset_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.BufferedWriter</returns>
    public JObject* GetTextOut()
    {
        var result = _env->GetObjectField(Object, textOut_FieldId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.OutputStreamWriter</returns>
    public JObject* GetCharOut()
    {
        var result = _env->GetObjectField(Object, charOut_FieldId);
        return result;
    }
    public bool GetClosing()
    {
        var result = _env->GetBooleanField(Object, closing_FieldId);
        return result;
    }

    public void SetAutoFlush(bool value)
    {
        _env->SetBooleanField(Object, autoFlush_FieldId, value);
    }
    public void SetTrouble(bool value)
    {
        _env->SetBooleanField(Object, trouble_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.util.Formatter</param>
    
    public void SetFormatter(JObject* value)
    {
        _env->SetObjectField(Object, formatter_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.nio.charset.Charset</param>
    
    public void SetCharset(JObject* value)
    {
        _env->SetObjectField(Object, charset_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.io.BufferedWriter</param>
    
    public void SetTextOut(JObject* value)
    {
        _env->SetObjectField(Object, textOut_FieldId, value);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="value">java.io.OutputStreamWriter</param>
    
    public void SetCharOut(JObject* value)
    {
        _env->SetObjectField(Object, charOut_FieldId, value);
    }
    public void SetClosing(bool value)
    {
        _env->SetBooleanField(Object, closing_FieldId, value);
    }

    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg1">java.io.OutputStream</param>
    public static PrintStream PrintStream0_Constructor(JniEnv* env, bool arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].Z = (byte)(arg0 ? 1 : 0);
        args[1].L = arg1;

        var result = env->NewObjectA(Class, PrintStream0_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg1">java.nio.charset.Charset</param>
    /// <param name="arg2">java.io.OutputStream</param>
    public static PrintStream PrintStream1_Constructor(JniEnv* env, bool arg0, JObject* arg1, JObject* arg2)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[3];
        args[0].Z = (byte)(arg0 ? 1 : 0);
        args[1].L = arg1;
        args[2].L = arg2;

        var result = env->NewObjectA(Class, PrintStream1_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.OutputStream</param>
    public static PrintStream PrintStream2_Constructor(JniEnv* env, JObject* arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = env->NewObjectA(Class, PrintStream2_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.OutputStream</param>
    public static PrintStream PrintStream3_Constructor(JniEnv* env, JObject* arg0, bool arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].Z = (byte)(arg1 ? 1 : 0);

        var result = env->NewObjectA(Class, PrintStream3_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.OutputStream</param>
    /// <param name="arg2">java.lang.String</param>
    public static PrintStream PrintStream4_Constructor(JniEnv* env, JObject* arg0, bool arg1, string arg2)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[3];
        args[0].L = arg0;
        args[1].Z = (byte)(arg1 ? 1 : 0);
        JObject* stringArg2 = (JObject*)env->NewStringUTF(arg2);
        args[2].L = stringArg2;

        var result = env->NewObjectA(Class, PrintStream4_MethodId, args);
        env->DeleteLocalRef(stringArg2);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.OutputStream</param>
    /// <param name="arg2">java.nio.charset.Charset</param>
    public static PrintStream PrintStream5_Constructor(JniEnv* env, JObject* arg0, bool arg1, JObject* arg2)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[3];
        args[0].L = arg0;
        args[1].Z = (byte)(arg1 ? 1 : 0);
        args[2].L = arg2;

        var result = env->NewObjectA(Class, PrintStream5_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    public static PrintStream PrintStream6_Constructor(JniEnv* env, string arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->NewObjectA(Class, PrintStream6_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <param name="arg1">java.lang.String</param>
    public static PrintStream PrintStream7_Constructor(JniEnv* env, string arg0, string arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->NewObjectA(Class, PrintStream7_MethodId, args);
        env->DeleteLocalRef(stringArg0);
         env->DeleteLocalRef(stringArg1);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    public static PrintStream PrintStream8_Constructor(JniEnv* env, string arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;
        args[1].L = arg1;

        var result = env->NewObjectA(Class, PrintStream8_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.File</param>
    public static PrintStream PrintStream9_Constructor(JniEnv* env, JObject* arg0)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = env->NewObjectA(Class, PrintStream9_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.File</param>
    /// <param name="arg1">java.lang.String</param>
    public static PrintStream PrintStream10_Constructor(JniEnv* env, JObject* arg0, string arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        JObject* stringArg1 = (JObject*)env->NewStringUTF(arg1);
        args[1].L = stringArg1;

        var result = env->NewObjectA(Class, PrintStream10_MethodId, args);
        env->DeleteLocalRef(stringArg1);

        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.io.File</param>
    /// <param name="arg1">java.nio.charset.Charset</param>
    public static PrintStream PrintStream11_Constructor(JniEnv* env, JObject* arg0, JObject* arg1)
    {
        Initialize(env);
        JValue* args = stackalloc JValue[2];
        args[0].L = arg0;
        args[1].L = arg1;

        var result = env->NewObjectA(Class, PrintStream11_MethodId, args);
        return new(env, result);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>java.nio.charset.Charset</returns>
    public static JObject* ToCharset(JniEnv* env, string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        var result = env->CallStaticObjectMethodA(Class, toCharset_MethodId, args);
        env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void EnsureOpen()
    {
        _env->CallVoidMethod(Object, ensureOpen_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Flush()
    {
        _env->CallVoidMethod(Object, flush_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Close()
    {
        _env->CallVoidMethod(Object, close_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>boolean</returns>
    public bool CheckError()
    {
        var result = _env->CallBooleanMethod(Object, checkError_MethodId);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void SetError()
    {
        _env->CallVoidMethod(Object, setError_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void ClearError()
    {
        _env->CallVoidMethod(Object, clearError_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Write(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        _env->CallVoidMethodA(Object, write0_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">byte[]</param>
    /// <returns>void</returns>
    public void Write(JByteArray* arg0, int arg1, int arg2)
    {
        JValue* args = stackalloc JValue[3];
        args[0].L = (JObject*)arg0;
        args[1].I = arg1;
        args[2].I = arg2;

        _env->CallVoidMethodA(Object, write1_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">byte[]</param>
    /// <returns>void</returns>
    public void Write(JByteArray* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = (JObject*)arg0;

        _env->CallVoidMethodA(Object, write2_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">char[]</param>
    /// <returns>void</returns>
    public void Write(JCharArray* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = (JObject*)arg0;

        _env->CallVoidMethodA(Object, write3_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>void</returns>
    public void Write(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        _env->CallVoidMethodA(Object, write4_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">byte[]</param>
    /// <returns>void</returns>
    public void WriteBytes(JByteArray* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = (JObject*)arg0;

        _env->CallVoidMethodA(Object, writeBytes_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">char[]</param>
    /// <returns>void</returns>
    public void Writeln(JCharArray* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = (JObject*)arg0;

        _env->CallVoidMethodA(Object, writeln0_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>void</returns>
    public void Writeln(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        _env->CallVoidMethodA(Object, writeln1_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void NewLine()
    {
        _env->CallVoidMethod(Object, newLine_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Print(bool arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].Z = (byte)(arg0 ? 1 : 0);

        _env->CallVoidMethodA(Object, print0_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Print(char arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].C = arg0;

        _env->CallVoidMethodA(Object, print1_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Print(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        _env->CallVoidMethodA(Object, print2_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Print(long arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].J = arg0;

        _env->CallVoidMethodA(Object, print3_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Print(float arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].F = arg0;

        _env->CallVoidMethodA(Object, print4_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Print(double arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].D = arg0;

        _env->CallVoidMethodA(Object, print5_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">char[]</param>
    /// <returns>void</returns>
    public void Print(JCharArray* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = (JObject*)arg0;

        _env->CallVoidMethodA(Object, print6_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>void</returns>
    public void Print(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        _env->CallVoidMethodA(Object, print7_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.Object</param>
    /// <returns>void</returns>
    public void Print(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        _env->CallVoidMethodA(Object, print8_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Println()
    {
        _env->CallVoidMethod(Object, println0_MethodId);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Println(bool arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].Z = (byte)(arg0 ? 1 : 0);

        _env->CallVoidMethodA(Object, println1_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Println(char arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].C = arg0;

        _env->CallVoidMethodA(Object, println2_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Println(int arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].I = arg0;

        _env->CallVoidMethodA(Object, println3_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Println(long arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].J = arg0;

        _env->CallVoidMethodA(Object, println4_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Println(float arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].F = arg0;

        _env->CallVoidMethodA(Object, println5_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>void</returns>
    public void Println(double arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].D = arg0;

        _env->CallVoidMethodA(Object, println6_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">char[]</param>
    /// <returns>void</returns>
    public void Println(JCharArray* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = (JObject*)arg0;

        _env->CallVoidMethodA(Object, println7_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <returns>void</returns>
    public void Println(string arg0)
    {
        JValue* args = stackalloc JValue[1];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;

        _env->CallVoidMethodA(Object, println8_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.Object</param>
    /// <returns>void</returns>
    public void Println(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        _env->CallVoidMethodA(Object, println9_MethodId, args);
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <param name="arg1">java.lang.Object...</param>
    /// <returns>java.io.PrintStream</returns>
    public JObject* Printf(string arg0, JObjectArray* arg1)
    {
        JValue* args = stackalloc JValue[2];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;
        args[1].L = (JObject*)arg1;

        var result = _env->CallObjectMethodA(Object, printf0_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.Locale</param>
    /// <param name="arg1">java.lang.String</param>
    /// <param name="arg2">java.lang.Object...</param>
    /// <returns>java.io.PrintStream</returns>
    public JObject* Printf(JObject* arg0, string arg1, JObjectArray* arg2)
    {
        JValue* args = stackalloc JValue[3];
        args[0].L = arg0;
        JObject* stringArg1 = (JObject*)_env->NewStringUTF(arg1);
        args[1].L = stringArg1;
        args[2].L = (JObject*)arg2;

        var result = _env->CallObjectMethodA(Object, printf1_MethodId, args);
        _env->DeleteLocalRef(stringArg1);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.String</param>
    /// <param name="arg1">java.lang.Object...</param>
    /// <returns>java.io.PrintStream</returns>
    public JObject* Format(string arg0, JObjectArray* arg1)
    {
        JValue* args = stackalloc JValue[2];
        JObject* stringArg0 = (JObject*)_env->NewStringUTF(arg0);
        args[0].L = stringArg0;
        args[1].L = (JObject*)arg1;

        var result = _env->CallObjectMethodA(Object, format0_MethodId, args);
        _env->DeleteLocalRef(stringArg0);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.util.Locale</param>
    /// <param name="arg1">java.lang.String</param>
    /// <param name="arg2">java.lang.Object...</param>
    /// <returns>java.io.PrintStream</returns>
    public JObject* Format(JObject* arg0, string arg1, JObjectArray* arg2)
    {
        JValue* args = stackalloc JValue[3];
        args[0].L = arg0;
        JObject* stringArg1 = (JObject*)_env->NewStringUTF(arg1);
        args[1].L = stringArg1;
        args[2].L = (JObject*)arg2;

        var result = _env->CallObjectMethodA(Object, format1_MethodId, args);
        _env->DeleteLocalRef(stringArg1);

        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.CharSequence</param>
    /// <returns>java.io.PrintStream</returns>
    public JObject* Append(JObject* arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].L = arg0;

        var result = _env->CallObjectMethodA(Object, append0_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.CharSequence</param>
    /// <returns>java.io.PrintStream</returns>
    public JObject* Append(JObject* arg0, int arg1, int arg2)
    {
        JValue* args = stackalloc JValue[3];
        args[0].L = arg0;
        args[1].I = arg1;
        args[2].I = arg2;

        var result = _env->CallObjectMethodA(Object, append1_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.io.PrintStream</returns>
    public JObject* Append(char arg0)
    {
        JValue* args = stackalloc JValue[1];
        args[0].C = arg0;

        var result = _env->CallObjectMethodA(Object, append2_MethodId, args);
        return result;
    }
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.lang.Appendable</returns>
    //public JObject* Append(char arg0)
    //{
    //    JValue* args = stackalloc JValue[1];
    //    args[0].C = arg0;

    //    var result = _env->CallObjectMethodA(Object, append3_MethodId, args);
    //    return result;
    //}
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.CharSequence</param>
    /// <returns>java.lang.Appendable</returns>
    //public JObject* Append(JObject* arg0, int arg1, int arg2)
    //{
    //    JValue* args = stackalloc JValue[3];
    //    args[0].L = arg0;
    //    args[1].I = arg1;
    //    args[2].I = arg2;

    //    var result = _env->CallObjectMethodA(Object, append4_MethodId, args);
    //    return result;
    //}
    /// <summary>
    /// To be documented
    /// </summary>
    /// <param name="arg0">java.lang.CharSequence</param>
    /// <returns>java.lang.Appendable</returns>
    //public JObject* Append(JObject* arg0)
    //{
    //    JValue* args = stackalloc JValue[1];
    //    args[0].L = arg0;

    //    var result = _env->CallObjectMethodA(Object, append5_MethodId, args);
    //    return result;
    //}
    /// <summary>
    /// To be documented
    /// </summary>
    /// <returns>java.nio.charset.Charset</returns>
    public JObject* Charset()
    {
        var result = _env->CallObjectMethod(Object, charset_MethodId);
        return result;
    }
}